### ISSUE TITLE
Missing package in the build environment causes build failure for the `kselftest/alsa/mixer-test` test

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-core#1013]
A correct package needs to be identified. It needs to be added to the build container.
```
ccache gcc     mixer-test.c  -o /tmp/kci/linux/build/kselftest/alsa/mixer-test
mixer-test.c:24:10: fatal error: alsa/asoundlib.h: No such file or directory
   24 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

Reference logs: https://storage.staging.kernelci.org/next/master/next-20220128/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-10/logs/kselftest.log

**Comment by gctucker** [comment]
I see, this needs to be added to the Docker images used for kselftest builds (basically, the gcc-10 ones for `arm`, `arm64` and `x86`). For example:
https://github.com/kernelci/kernelci-core/blob/main/config/docker/gcc-10_x86/Dockerfile
