### ISSUE TITLE
[clang] additional trees/branches

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#103]
per our discussion on the mailing list, I think it would be worthwhile to expand testing coverage of defconfigs from -next to mainline, and stable for 4.19, 4.14, 4.9, and maybe 4.4 (we do support arm64 and x86_64 defconfigs back to 4.4).

**Comment by broonie** [comment]
I'm unconvinced about stable as it'd seem better to expand stable coverage to include allmodconfig (which IIRC we dropped for builder resource) as at present a bunch of stable isn't getting tested at all.

**Comment by nickdesaulniers** [comment]
allmodconfig SGTM; getting some coverage of stable is important.

**Comment by broonie** [comment]
There's outstanding issues with the UI for clang reports that we probably want to address before rolling this out to more trees:

https://github.com/kernelci/kernelci-core/issues/127
https://github.com/kernelci/kernelci-frontend/issues/44

It also looks like arm64 big endian boots are broken with clang, that probably needs looking at too.

**Comment by mattface** [comment]
Since boots were disabled for clang, issue #127 isn't a blocker for these additional trees and branches builds to be added.

**Comment by gctucker** [comment]
So, should we add arm64 defconfig and x86_64_defconfig on stable 4.9, 4.14, 4.19 with clang-8?

Adding allmodconfig to all the stable branches for arm64 and x86, and on top of that both for gcc and clang would mean a significant increase in build time.  I think there's still enough headroom for it but we need to be sure it's really worth it and if so then we may soon need to add more builders or reduce the build coverage on other branches.

**Comment by nickdesaulniers** [comment]
Yes please, but can we move to clang-9 for all clang builds?

**Comment by broonie** [comment]
Since clang-8 is supported upstream for at least arm64 and is shipping in released distributions like Debian it seems good to keep that, especially since features are being added to newer versions of clang and it's likely we'll get breakage for users if those aren't properly version guarded. 

Ideally we'd be able to support multiple versions of compilers...

**Comment by gctucker** [comment]
Yes we can add clang-9, which would mean more build power of course but if it's only -next master then it should be fine.  There were issues with the Docker image for clang-9 though so we would need to get that back on track first.

Sounds like it's worth a separate Github issue (for clang-9).
