### ISSUE TITLE
[clang] enable lld

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#104]
per a discussion today with Arnd, it would be good to make the clang builds use `LD=ld.lld` for their linkers.  The kernel really stresses LLD's linker script support, so it would be good to get it under coverage soon.  Should work with arm64.

**Comment by nickdesaulniers** [comment]
Also, probably need to verify that `ld.lld` is packaged in the docker images.

**Comment by nickdesaulniers** [comment]
Also, the TCWG @ linaro is also testing with Clang+LLD on by default.

**Comment by broonie** [comment]
Unless upstream arranges for clang builds to use lld by default we should probably keep coverage of builds with GNU LD since that's what people will be building if they just decide to go and build with clang. Testing with lld would definitely be good and I'm all in favour of adding it, I just worry about loosing coverage of the more standard case.

A reference to the discussion with Arnd would be helpful.

**Comment by nickdesaulniers** [comment]
> A reference to the discussion with Arnd would be helpful.

Video call, unrecorded.

> Unless upstream arranges for clang builds to use lld by default we should probably keep coverage of builds with GNU LD since that's what people will be building if they just decide to go and build with clang.

Sure if someone just does `make CC=clang` then clang will likely use `ld.bfd` (it needs a CMake variable `-DCLANG_DEFAULT_LINKER=lld`.

But we'd like to build the kernel with more than just clang; we'd like to use all llvm utilities so we can catch regressions in them.

I agree that `make CC=clang LD=ld.lld NM=llvm-nm ...` will get burdensome eventually, and have a few ideas to simplify that in Kbuild.

In the meantime, we'd really like to get testing coverage with lld.

**Comment by gctucker** [comment]
Maybe we could build a handful of defconfigs with an `llvm` build environment, as well as the current `clang` ones?

I think this could be defined as part of the Docker image used to do the kernel builds (Debian alternatives, or env variables set up before calling make...).

**Comment by kees** [comment]
> Maybe we could build a handful of defconfigs with an `llvm` build environment, as well as the current `clang` ones?

An "all LLVM tools" option now exists by setting LLVM=1 on the "make" command line. So now we could do GCC+bfd, Clang+bfd, and Clang+lld+all-other-LLVM-tools.

**Comment by gctucker** [comment]
Sounds like something we should be trying with linux-next on staging.
