### ISSUE TITLE
kselftests: Fix `pkg-config` errors for `kselftest/alsa`

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-core#1040]
The following error appears on cross-compiling with gcc, using clang-10, 11, 12 or 15 for kselftests/alsa:
```
make[1]: Entering directory '/tmp/kci/linux/tools/testing/selftests/alsa'
/usr/bin/pkg-config: 1: Syntax error: word unexpected (expecting ")")
/usr/bin/pkg-config: 1: Syntax error: word unexpected (expecting ")")
```
This error doesn't appear if gcc is used for x86 or clang-14 is used.

Ref: https://github.com/kernelci/kernelci-core/pull/1033#issuecomment-1035468432

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
