### ISSUE TITLE
Some kselftests need clang even in the gcc's environment

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-core#1064]
tc-testing kselftest requires clang for its compilation. But in KernelCI, we don't have clang in the build container if the container has some version of GCC. Hence we get the build error:
```
make[1]: Entering directory '/tmp/kci/linux/tools/testing/selftests/tc-testing'
/bin/sh: 1: llc: not found
clang -I. -I/include/uapi  -Wno-compare-distinct-pointer-types \
	 -O2 -target bpf -emit-llvm -c action.c -o - |      \
llc -march=bpf -mcpu=probe  -filetype=obj -o /tmp/kci/linux/build/kselftest/tc-testing/action.o
/bin/sh: 1: clang: not found
/bin/sh: 3: llc: not found
make[1]: *** [Makefile:27: /tmp/kci/linux/build/kselftest/tc-testing/action.o] Error 127
make[1]: Leaving directory '/tmp/kci/linux/tools/testing/selftests/tc-testing'
```
Ref: https://storage.staging.kernelci.org/next/master/next-20220304/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-10/logs/kselftest.log

It'll seem odd if we start installing clang to our GCC containers just to fix the build of this test and some other tests. These tests are mostly eBPF tests or related. If we don't want to do this in KernelCI, we should report a problem or add support in kselftests' build system to ignore building the tests which need clang when the default compiler is GCC and vice versa.

**Comment by gctucker** [comment]
What we really should have is a separate Docker image for building kselftests. That is in principle possible now that we have separate build commands in `kci_build` but some pipeline integration with Kubernetes jobs still needs to be done. We would also need to refactor the Dockerfiles a bit.

Also, there's a config to disable eBPF kselftests for this kind of reason. It doesn't just rely on Clang, but a very recent and specific version.  See this commit:
```
commit 7a6eb7c34a78498742b5f82543b7a68c1c443329
Author: Mark Brown <broonie@kernel.org>
Date:   Thu Dec 10 18:52:33 2020 +0000

    selftests: Skip BPF seftests by default
```

So maybe the `tc-testing` tests you've found should also be included in `SKIP_TARGETS` like the `bpf` ones?

**Comment by gctucker** [comment]
Meanwhile, I've hit this issue again and I'm now preparing a patch series to address this in the kernel.  I'll post some updates here once I've sent it.

**Comment by gctucker** [comment]
I did prepare a patch series but didn't get the time to send it.  In the meantime, I believe someone else from the Clang-built-Linux team has made some progress there so I'll take another look at the whole thing again.

**Comment by gctucker** [comment]
Replaced with issue in my kernel fork.
