### ISSUE TITLE
gcc10 is partially broken on bullseye/x86

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1067]
Right now we have build error appearing on some kernels:
https://storage.kernelci.org/mainline/master/v5.17-rc7/x86_64/allmodconfig/gcc-10/logs/build-errors.log
"/usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory"

Turned out that gcc10 in bullseye is broken for long time: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980609
Possible solutions discussed:
> Using sid gcc-10 (it is fixed)
> Applying patch(workaround) in docker image: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980609#72
> Using some other gcc-10 toolchain?

**Comment by gctucker** [comment]
Is there a gcc-10 backport package for Bullseye with the fix?

**Comment by nuclearcat** [comment]
As far as i can see nothing in bullseye-backports, verified in repo and at https://packages.debian.org/bullseye-backports/devel/
One more note, it breaks only if gcc plugins are enabled in kernel config (as it is done in allmodconfig).

+CONFIG_GCC_PLUGIN_LATENT_ENTROPY=y
+CONFIG_GCC_PLUGIN_RANDSTRUCT=y
+CONFIG_GCC_PLUGIN_STACKLEAK=y
+CONFIG_STACKLEAK_TRACK_MIN_SIZE=100
+CONFIG_STACKLEAK_METRICS=y
+CONFIG_STACKLEAK_RUNTIME_DISABLE=y

**Comment by nuclearcat** [comment]
Fixed by https://github.com/kernelci/kernelci-core/pull/1078
