### ISSUE TITLE
build.py: switch to dtbs_install

### ISSUE THREAD

**Issue by khilman** [kernelci/kernelci-core#12]
Since v4.19(ish), the kernel has support for `make dtbs_install`, we should use that (when available) instead of the current manual copy.

**Comment by gctucker** [comment]
It's still relevant, the current code in `kernelci.build` still does a manual copy of all the files.  Now we're building kernels older than v4.9 we should be able to adopt it.  If we don't update the code for the current builds, we should use this approach with the new kernel build jobs.
