### ISSUE TITLE
Enable Landlock kselftests

### ISSUE THREAD

**Issue by l0kod** [kernelci/kernelci-core#1235]
Could you please add [landlock](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/tools/testing/selftests/landlock) to the currently enabled kselftests? I'm the maintainer of Landlock and I would like to get any related test issues.

**Comment by broonie** [comment]
I've created a pull request https://github.com/kernelci/kernelci-core/pull/1236 with some initial enablement on a couple of boards which should hopefully get things running at least (it'll initially start in our staging instance, assuming I didn't mess the config up.
