### ISSUE TITLE
LAVA job links

### ISSUE THREAD

**Issue by broonie** [kernelci/kernelci-core#124]
For debugging issues in labs it's sometimes helpful to be able to trace things through to the specific LAVA job in the relevant lab (for confirming exactly what board something got run on for example) but currently we don't record much about the jobs or make anything (eg, a link) available in the UI to support this tracing. It'd be good to add this, we get the LAVA job description in the callback so we could record it easily enough and then let the UI pull things up.

@mattface @gctucker

**Comment by gctucker** [comment]
There are some potential issues with this:
* some labs don't have a public LAVA web UI, so there can't be public links to these jobs
* some old jobs may be archived after a while, I know we do this on the Collabora LAVA server

So there could be a "best effort" URL if that helps, which might cause people to report problems if it doesn't work.  Maybe we could just show the LAVA job number, so if you have access to the lab (public or not) then you can trace it back.

**Comment by broonie** [comment]
We could always have a flag for each lab which says if the web UI is public and only generates a link if that's the case - show the job number always and make it a link if the UI is there. I do think we should use a link if we can, it's an obvious thing to do and people will wonder why it's not a link in cases where it's useful.

Given that we don't keep much history on the KernelCI server I'm not sure jobs getting archived is a pressing issue, I suspect the jobs will vanish from KernelCI before the labs.

**Comment by gctucker** [comment]
True, jobs are only available for a few weeks on kernelci.org.

There's the `labs.ini` file in kernelci-core, we could add a flag there to enable jobs URLs or not.

We could also check that the URL is valid and available when receiving a LAVA callback in the backend, to automatically determine if it should be featured on the frontend.

**Comment by broonie** [comment]
I thought about checking at submission time if the link works but I thought that might give false positives in cases where the lab has a firewall or other access configuration that gives the master server access but not random internet addresses.

**Comment by danrue** [comment]
One other issue is that job ids aren't necessarily unique; I know @mattface will delete the database and start over occasionally, which would cause links to go to incorrect jobs over time. Makes me wonder if LAVA should use something more unique than a sequential ID for jobs...

**Comment by broonie** [comment]
With the short history you'd need to be deleting the database pretty often to hit any actual collisions I guess?
