### ISSUE TITLE
 >1 pod found with job name XXX (duplicate pods?)

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1251]
For 2 repeating days i noticed some of builds have warning:
For example: https://bot.staging.kernelci.org/job/chromeos/job/kernel-build/10243/console
Which is Jun 9 morning:
WARNING: >1 pod found with job name build-j10243-arm64-clang-14-defconfig-arm64-chromebook

After checking jenkins, as i see that for last 24h we run only one job that match such name (defconfig-arm64-chromebook).

**Comment by gctucker** [comment]
The Jenkins log is gone, next time please attach the plain text log as a file.

**Comment by broonie** [comment]
If a node gets preempted due to being a spot instances the job will ned the pod recreating - it should have a different suffix added to the job name though

**Comment by gctucker** [comment]
@nuclearcat Is this still an issue?  Do you have any insight as to why it might be happening?

**Comment by nuclearcat** [comment]
Very rare, but happens. Partially addressed in: https://github.com/kernelci/kernelci-core/pull/1479
Problem is that it happen much less now, so maybe better to close issue, unless we need to address it again - we can reopen it.

**Comment by gctucker** [comment]
Right, I think that's probably wise so the workboard only contains things that actually require some attention.

**Comment by nuclearcat** [comment]
Thanks, closing issue for now
