### ISSUE TITLE
modules dependencies are missing in kernels with enabled modules compression

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1256]
During troubleshooting upstream kernel boot issues on ChromeOS i found that modprobe failing to find kernel modules if kernel is compiled with modules gzip compression enabled.
( CONFIG_MODULE_COMPRESS + CONFIG_MODULE_COMPRESS_GZIP )
Example: i can "insmod /path/e1000e.ko.gz" specifying full path to module, but "modprobe e1000e" will fail with error module not found.

After investigation i found that modules.tar.xz we generate doesnt have proper modules dependencies (for example: modules.dep size is 0 bytes).
Troubleshooting hinted me that problem is in Debian bullseye kmod utilities we are using, they are built with following options:
```
kmod version 28
-ZSTD +XZ -ZLIB +LIBCRYPTO -EXPERIMENTAL 
```
To generate modules.dep kmod should be built with compression method support, in this particular case ZLIB.
Experimentally i built kmod manually with ZLIB support and indeed it started to generate proper modules.dep

**Comment by nuclearcat** [comment]
PR pushed https://github.com/kernelci/kernelci-core/pull/1288

**Comment by nuclearcat** [comment]
Updated PR: https://github.com/kernelci/kernelci-core/pull/1318
And additional measure: https://github.com/kernelci/kernelci-core/pull/1306

**Comment by gctucker** [comment]
> Updated PR: #1318 And additional measure: #1306

Please link the PRs to this issue.

**Comment by nuclearcat** [comment]
Done
