### ISSUE TITLE
kci_docker

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1335]
The standard Dockerfile syntax doesn't allow the flexibility required by KernelCI Docker images as there are many combinations of toolchains, KernelCI tools and extra build dependencies for kselftest, kunit etc.  A solution to this is to use Jinja2 templates with a Python tool to build images more dynamically.

- [x] #1320 (initial version)
- [x] Extra Dockerfile fixes ported from current `config/docker`
- [x] #1380 Add `qemu` image
- [x] Add rootfs build images
  -  #1377 
  - #1378
- [x] Add other images used for tests
  - #1383 
  - #1382 
- [x] #1454
- [x] https://github.com/kernelci/kernelci-deploy/commit/f043f71f8f439012f85806f1f499772452d4f44c Update automated build & push logic for new images
- [x] https://github.com/kernelci/kernelci-jenkins/pull/97
- [x] https://github.com/kernelci/kernelci-core/commit/d41d1072aa9d0e9b2c895fd15882a385cace5b2f Update documentation, rework `kci_docker` CLI if needed
- [x] remove old config
  - #1417 
  - #1436
  - ~~#1718~~ Not required for closing this task, it's a ChromeOS-specific one.

**Comment by nuclearcat** [comment]
I think only thing remain to delete old docker configs?
