### ISSUE TITLE
kci_build run error

### ISSUE THREAD

**Issue by piaoxuebingfeng** [kernelci/kernelci-core#1354]
i use latest kernelci-core

i use kci_build such as  this link https://static.staging.kernelci.org/docs/core/kci_build/
 but i got  errors.

```
./kci_build init_bmeta --build-config=next --build-env=gcc-8 --arch=x86_64
Initialising build meta-data in linux/build

Install directory: linux/build/_install_
Traceback (most recent call last):
  File "./kci_build", line 427, in <module>
    status = opts.command(configs, opts)
  File "./kci_build", line 322, in __call__
    build_env = configs['build_environments'][args.build_env]
KeyError: 'gcc-8'
```
i do not know how to resolve it,who can tell me how to resolve this question?

**Comment by gctucker** [comment]
The default GCC version used by KernelCI is not `gcc-8` any more but `gcc-10`.  The examples in the docs need to be updated accordingly.

If you replace `gcc-8` by `gcc-10` in your `kernelci.conf` or in the `--build-env` argument then it should work.  You also need to get the matching Docker image for `gcc-10` to run the actual kernel build.

**Comment by piaoxuebingfeng** [comment]
> The default GCC version used by KernelCI is not `gcc-8` any more but `gcc-10`. The examples in the docs need to be updated accordingly.
> 
> If you replace `gcc-8` by `gcc-10` in your `kernelci.conf` or in the `--build-env` argument then it should work. You also need to get the matching Docker image for `gcc-10` to run the actual kernel build.

got it ,thanks!

**Comment by gctucker** [comment]
@piaoxuebingfeng I've updated the docs to use `gcc-10`, see the staging version of the website:
https://static.staging.kernelci.org/docs/core/kci_build/

Please feel free to leave a comment on the PR if it looks OK and it'll get merged:
https://github.com/kernelci/kernelci-core/pull/1358
