### ISSUE TITLE
ChromeOS: ensure proper cfg fragments are used for various kernels

### ISSUE THREAD

**Issue by 10ne1** [kernelci/kernelci-core#1371]
[build-configs-chromeos.yaml](https://github.com/kernelci/kernelci-core/blob/main/config/core/build-configs-chromeos.yaml) defines the use of v5.10 CrOS config fragments for all kernels, but I think it's a bad idea to use the v5.10 fragments to build 5.15, mainline and so on kernels, because it can lead to unforeseen failures.

This can also be seen in the test results, for eg [this one](https://chromeos.kernelci.org/test/plan/id/62f9b3f43da8979c5530d7d6/) if you click on the defconfig and compare revisions, you notice the 5.10 cfg is used to build the 5.15 kernel.

Each downstream ChromeOS kernel version supplies its own config fragments (eg 5.15 is [here](https://chromium.googlesource.com/chromiumos/third_party/kernel/+/refs/heads/chromeos-5.15/chromeos/config/chromeos) ) which should be possible to fetch via the `cros://` links mechanism used by KernelCI.

So ideally we would use the 5.10 cfg for 5.10, 5.15 for 5.15, "upstream" for the mainline branch etc.

**Comment by nuclearcat** [comment]
Here is relevant PR: https://github.com/kernelci/kernelci-core/pull/1366 that need some fixing

**Comment by nuclearcat** [comment]
Fixed by #1400
