### ISSUE TITLE
kci_data run error

### ISSUE THREAD

**Issue by piaoxuebingfeng** [kernelci/kernelci-core#1374]
./kci_data submit_build --db-config=localhost --kdir=linux
400 Client Error: Provided JSON is not valid for url: http://localhost:8081/build

**Comment by piaoxuebingfeng** [comment]
> Well that can't be investigated without also providing the JSON data you're trying to submit.
I'm a novice.
i use `kci_data ` reference to `https://kernelci.org/docs/core/kci_build/` ,but i do not know how to generate the JSON data.can you tell me how to generate the json data?

**Comment by gctucker** [comment]
The JSON data is generated by `kci_build` while making a kernel build.

**Comment by piaoxuebingfeng** [comment]
> The JSON data is generated by `kci_build` while making a kernel build.

well,i run `./kci_build init_bmeta --build-config=next` to generate the json file to path `linux/build-x86`,and the files are `bmeta.json` `steps.json` and `artifacts.json`.is this `bmeta.json` the json data? 
the `bmeta.json` data is:
`{
    "build": {
        "duration": 5.357404947280884,
        "status": "PASS"
    },
    "environment": {
        "arch": "x86_64",
        "compiler": "gcc",
        "compiler_version": "10",
        "compiler_version_full": "gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0",
        "cross_compile": "",
        "cross_compile_compat": "",
        "make_opts": {
            "KBUILD_BUILD_USER": "KernelCI"
        },
        "name": "gcc-10",
        "platform": {
            "uname": [
                "Linux",
                "ubuntu-kernelci",
                "5.4.0-26-generic",
                "#30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020",
                "x86_64",
                "x86_64"
            ]
        },
        "use_ccache": false
    },
    "revision": {
        "branch": "master",
        "commit": "fa96acf505e0e5f4774e273d97cee65fffcf53e6",
        "describe": "next-20220815",
        "describe_verbose": "v5.19-15376-gfa96acf505e0",
        "tree": "next",
        "url": "https://mirrors.tuna.tsinghua.edu.cn/git/linux-next.git"
    }
}`
then,i run `./kci_data submit_build` ,the response is :
`
# ./kci_data submit_build --kdir=linux
400 Client Error: Provided JSON is not valid for url: http://localhost:8081/build
One or more mandatory keys are missing: ['defconfig', 'git_branch', 'arch', 'kernel', 'job']
` 
is this correct?

**Comment by gctucker** [comment]
That's just the first step, after `init_bmeta` you need to build the kernel with `make_config` and `make_kernel`. Then there will be a kernel image, you need that in order to submit a build to the database.

**Comment by piaoxuebingfeng** [comment]
yes.
i have built the kernel ,and i push the kernel to the stiorage ,now.i run the `kci_build` as this:
```
./kci_build update_mirror --build-config=next --mirror=linux-mirror.git
./kci_build update_repo --build-config=next --mirror=linux-mirror.git --kdir=linux
./kci_build generate_fragments --build-config=next --kdir=linux
./kci_build init_bmeta --build-config=next --kdir=linux

docker run -it -v $PWD:/root/kernelci-core kernelci/gcc-10_x86 /bin/bash
cd /root/kernelci-core
./kci_build make_config --defconfig=defconfig
./kci_build make_kernel
./kci_build make_modules

exit

./kci_build push_kernel --kdir=linux --api=http://localhost:8081  --db-token=13a50e11-b572-41c2-9c62-bda7f9f73fe6

./kci_data submit_build
``` 

now my question is ,when i run kci_data cmd,i got the error .

**Comment by gctucker** [comment]
Could you please attach your `bmeta.json` file in a comment here so we can check if there's anything missing?

**Comment by piaoxuebingfeng** [comment]
```
{
    "build": {
        "duration": 243.71062874794006,
        "status": "PASS"
    },
    "environment": {
        "arch": "x86_64",
        "compiler": "gcc",
        "compiler_version": "10",
        "compiler_version_full": "gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0",
        "cross_compile": "",
        "cross_compile_compat": "",
        "make_opts": {
            "KBUILD_BUILD_USER": "KernelCI"
        },
        "name": "gcc-10",
        "platform": {
            "uname": [
                "Linux",
                "ubuntu-kernelci",
                "5.4.0-26-generic",
                "#30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020",
                "x86_64",
                "x86_64"
            ]
        },
        "use_ccache": false
    },
    "kernel": {
        "defconfig": "defconfig",
        "defconfig_expanded": "defconfig",
        "defconfig_extras": [],
        "defconfig_full": "defconfig",
        "endianness": "little",
        "image": "bzImage",
        "publish_path": "next/master/next-20220822/x86_64/defconfig/gcc-10",
        "text_offset": "0x01000000",
        "vmlinux_bss_size": 929792,
        "vmlinux_data_size": 2725760,
        "vmlinux_file_size": 74049216,
        "vmlinux_text_size": 16790152
    },
    "revision": {
        "branch": "master",
        "commit": "cc2986f4dc67df7e6209e0cd74145fffbd30d693",
        "describe": "next-20220822",
        "describe_verbose": "v6.0-rc1-2664-gcc2986f4dc67",
        "tree": "next",
        "url": "https://mirrors.tuna.tsinghua.edu.cn/git/linux-next.git"
    }
}r
```

**Comment by gctucker** [comment]
Thanks.  The error from the server was:
```
One or more mandatory keys are missing: ['defconfig', 'git_branch', 'arch', 'kernel', 'job']
```
but these keys are present in the `kernel` section of your JSON data.  So maybe you're not passing the correct path to the file with `--bmeta-json`?

**Comment by piaoxuebingfeng** [comment]
how to use `--bmeta-json`?

```
# ./kci_data submit_build --kdir=linux --bmeta-json=linux/build-x86/bmeta.json
usage: kci_data [-h] [--yaml-config YAML_CONFIG] [--settings SETTINGS] {validate,list_configs,submit,submit_build,submit_test} ...
kci_data: error: unrecognized arguments: --bmeta-json=linux/build-x86/bmeta.json

```
this is error.

the `bmeta.json`  is at `linux/build-x86/` path .

**Comment by gctucker** [comment]
Ah I think that's because the build steps were run without the `--install` argument.  It copies all the files needed for sending the build to the database in a separate directory which can then be used by `kci_data`.

Then `./kci_data submit_build --output=linux/build-x86` should send the files located in `linux/build-x86/_install_`.  You could copy the files there by hand, but it's probably better to run all the `kci_build` commands again with `--install` to get this done automatically.  It shouldn't cause a new kernel build from scratch.

I guess this is something that could be improved, by always copying the files in the install directory.

**Comment by piaoxuebingfeng** [comment]
i don't understand.

```
./kci_data submit_build --output=linux/build-x86 --kdir=linux
400 Client Error: Provided JSON is not valid for url: http://localhost:8081/build
One or more mandatory keys are missing: ['defconfig', 'git_branch', 'arch', 'kernel', 'job']
```

**Comment by gctucker** [comment]
That's because there's no file in `linux/build-x86/_install_`.  It's probably missing an error message in `kci_data` to say the file was not found, as I think it might just be loading empty build meta-data without the file.

**Comment by piaoxuebingfeng** [comment]
i modify the `output` path to `./linux` ,and then,i rebuild the kernel .
now,in `linux/_install_` have these files:
```
# ls linux/_install_/
artifacts.json  bmeta.json  config  kernel  kselftest.tar.xz  logs  modules.tar.xz  steps.json

``` 
and then,i print the meta-data at `kci_data submit_build` ,such as:
```
# ./kci_data submit_build --kdir=linux --output=linux
{'bmeta': {'build': {'duration': 247.3617079257965, 'status': 'PASS'}, 'environment': {'arch': 'x86_64', 'compiler': 'gcc', 'compiler_version': '10', 'compiler_version_full': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0', 'cross_compile': '', 'cross_compile_compat': '', 'make_opts': {'KBUILD_BUILD_USER': 'KernelCI'}, 'name': 'gcc-10', 'platform': {'uname': ['Linux', 'ubuntu-kernelci', '5.4.0-26-generic', '#30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020', 'x86_64', 'x86_64']}, 'use_ccache': False}, 'kernel': {'defconfig': 'defconfig', 'defconfig_expanded': 'defconfig', 'defconfig_extras': [], 'defconfig_full': 'defconfig', 'endianness': 'little', 'image': 'bzImage', 'publish_path': 'next/master/next-20220822/x86_64/defconfig/gcc-10', 'text_offset': '0x01000000', 'vmlinux_bss_size': 929792, 'vmlinux_data_size': 2725760, 'vmlinux_file_size': 74049216, 'vmlinux_text_size': 16790152}, 'revision': {'branch': 'master', 'commit': 'cc2986f4dc67df7e6209e0cd74145fffbd30d693', 'describe': 'next-20220822', 'describe_verbose': 'v6.0-rc1-2664-gcc2986f4dc67', 'tree': 'next', 'url': 'https://mirrors.tuna.tsinghua.edu.cn/git/linux-next.git'}}, 'steps': [{'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 5.650191783905029, 'name': 'revision', 'start_time': '2022-08-23T09:27:20.627046', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 0.0011959075927734375, 'name': 'revision install', 'start_time': '2022-08-23T09:27:26.278203', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 0.01416635513305664, 'name': 'environment', 'start_time': '2022-08-23T09:27:26.282687', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 0.0012729167938232422, 'name': 'environment install', 'start_time': '2022-08-23T09:27:26.297797', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 3.8129260540008545, 'log_file': 'config.log', 'name': 'config', 'start_time': '2022-08-23T01:28:01.641648', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 0.0031189918518066406, 'log_file': 'config.log', 'name': 'config install', 'start_time': '2022-08-23T01:28:05.455684', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 136.78297781944275, 'log_file': 'kernel.log', 'name': 'kernel', 'start_time': '2022-08-23T01:28:10.343834', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 0.037878990173339844, 'log_file': 'kernel.log', 'name': 'kernel install', 'start_time': '2022-08-23T01:30:27.127914', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 3.428818941116333, 'log_file': 'modules.log', 'name': 'modules', 'start_time': '2022-08-23T01:32:51.993918', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 1.181032419204712, 'log_file': 'modules.log', 'name': 'modules install', 'start_time': '2022-08-23T01:32:55.423753', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 96.03883814811707, 'log_file': 'kselftest.log', 'name': 'kselftest', 'start_time': '2022-08-23T01:33:12.916704', 'status': 'PASS'}, {'cpus': {'Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz': 16}, 'duration': 0.4092895984649658, 'log_file': 'kselftest.log', 'name': 'kselftest install', 'start_time': '2022-08-23T01:34:48.956586', 'status': 'PASS'}], 'artifacts': {'config': [{'key': 'config', 'path': 'config/kernel.config', 'type': 'file'}, {'key': 'log', 'path': 'logs/config.log', 'type': 'file'}], 'kernel': [{'key': 'system_map', 'path': 'kernel/System.map', 'type': 'file'}, {'key': 'image', 'path': 'kernel/bzImage', 'type': 'file'}, {'key': 'log', 'path': 'logs/kernel.log', 'type': 'file'}], 'kselftest': [{'contents': ['alsa', 'breakpoints', 'capabilities', 'cgroup', 'clone3', 'core', 'cpu-hotplug', 'cpufreq', 'damon', 'drivers', 'drivers/dma-buf', 'efivarfs', 'exec', 'filesystems', 'filesystems/binderfs', 'filesystems/epoll', 'filesystems/fat', 'firmware', 'fpu', 'ftrace', 'ftrace/test.d', 'ftrace/test.d/00basic', 'ftrace/test.d/direct', 'ftrace/test.d/dynevent', 'ftrace/test.d/event', 'ftrace/test.d/ftrace', 'ftrace/test.d/instances', 'ftrace/test.d/kprobe', 'ftrace/test.d/preemptirq', 'ftrace/test.d/selftest', 'ftrace/test.d/tracer', 'ftrace/test.d/trigger', 'ftrace/test.d/trigger/inter-event', 'futex', 'futex/functional', 'gpio', 'intel_pstate', 'ipc', 'ir', 'kcmp', 'kselftest', 'landlock', 'lib', 'livepatch', 'lkdtm', 'membarrier', 'memfd', 'memory-hotplug', 'mincore', 'mount', 'mount_setattr', 'move_mount_set_group', 'mqueue', 'nci', 'net', 'net/af_unix', 'net/forwarding', 'net/mptcp', 'netfilter', 'nsfs', 'openat2', 'pid_namespace', 'pidfd', 'proc', 'pstore', 'ptrace', 'resctrl', 'rlimits', 'rseq', 'rtc', 'seccomp', 'sgx', 'sigaltstack', 'size', 'splice', 'static_keys', 'sync', 'syscall_user_dispatch', 'sysctl', 'timens', 'timers', 'tmpfs', 'tpm2', 'user', 'vDSO', 'x86', 'zram'], 'path': 'kselftest.tar.xz', 'type': 'tarball'}, {'key': 'log', 'path': 'logs/kselftest.log', 'type': 'file'}], 'modules': [{'contents': ['efivarfs.ko', 'iptable_nat.ko', 'nf_log_syslog.ko', 'x86_pkg_temp_thermal.ko', 'xt_LOG.ko', 'xt_MASQUERADE.ko', 'xt_addrtype.ko', 'xt_mark.ko', 'xt_nat.ko'], 'path': 'modules.tar.xz', 'type': 'tarball'}, {'key': 'log', 'path': 'logs/modules.log', 'type': 'file'}]}}
400 Client Error: Provided JSON is not valid for url: http://localhost:8081/build
One or more mandatory keys are missing: ['defconfig', 'git_branch', 'arch', 'kernel', 'job']
```
i got the same error.

**Comment by piaoxuebingfeng** [comment]
I think the meta-data field is incomplete, but I don't know how to generate a complete meta-data.

**Comment by gctucker** [comment]
Which version of `kernelci-backend` are you using?  It seems you might be running an old version not supported by `kci_data` any more.  The current backend version uses `jsonschema` to validate the data, linux.kernelci.org is running `06d0b954f5a6 Bump app version to 2022.2.0` so I think you should double check you're at the same revision.

See this part of the code where the `bmeta.json` schema is defined and this is then used to validate the input:
https://github.com/kernelci/kernelci-backend/blob/main/app/handlers/build.py#L73

If the validation fails, the server returns an error from `jsonschema` with the exact fields where the errors were.

It's a shame there's no API version check when running `kci_data`, but now we're putting our efforts on the new API instead [`kernelci-api`](https://github.com/kernelci/kernelci-api) which should eventually replace `kernelci-backend` in production.

**Comment by piaoxuebingfeng** [comment]
OK.Thanks.
I rebuild my kernelci-backend env and test.

**Comment by piaoxuebingfeng** [comment]
now i rebuild kernelCI env , `kernelci-backend` version is 2022.2.0 and `kernelci-fontend` version is 2021.6 .
then,i run `kci_data` and get resp:
```
# ./kci_data submit_build --kdir=linux --output=linux/build-x86/
{"reason":"Request accepted and being imported","code":202}
```
is this correct ?

but then ,i can't find the build data from the frontend web pages ,why?

**Comment by gctucker** [comment]
OK yes that means the build data has been added to the database.

Now, I really can't tell why you're not seeing the data on the frontend.  Are you seeing anything at all?  Are you running both the frontend and backend on the same host?

**Comment by nuclearcat** [comment]
Closing issue as no feedback available.
