### ISSUE TITLE
kci_build doesn't log commands to merge config fragements

### ISSUE THREAD

**Issue by broonie** [kernelci/kernelci-core#140]
A variant on #137 but one surprising thing in the output of kci_build is that it doesn't show the commands where frag.config is merged into whatever the base config is in the output. For example the log for https://storage.kernelci.org/next/master/next-20190808/arm64/defconfig+CONFIG_CPU_BIG_ENDIAN=y/clang-8/build.log just has the make command to generate defconfig and then the make command to start the actual build. This isn't as clear as it could be to someone trying to track down an issue.

```
#
# make KBUILD_BUILD_USER=KernelCI -C/home/buildslave/workspace/workspace/kernel-build@8/linux ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- HOSTCC=clang CC="ccache clang" O=build defconfig
#
make: Entering directory '/home/buildslave/workspace/workspace/kernel-build@8/linux'

...

*** Default configuration is based on 'defconfig'
#
# configuration written to .config
#
make[1]: Leaving directory '/home/buildslave/workspace/workspace/kernel-build@8/linux/build'
make: Leaving directory '/home/buildslave/workspace/workspace/kernel-build@8/linux'
#
# make KBUILD_BUILD_USER=KernelCI -C/home/buildslave/workspace/workspace/kernel-build@8/linux -j4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- HOSTCC=clang CC="ccache clang" O=build Image
#
```

**Comment by gctucker** [comment]
This was fixed in #157, the output of `merge_config.sh` is now also shown when running `kci_build` with `--verbose`.
