### ISSUE TITLE
+kselftest need to run baseline jobs

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1490]
As mentioned in https://github.com/kernelci/kernelci-core/pull/1236#issuecomment-1300546894 : 
```
 it would really help if we had baseline jobs running for the kselftest kernels but unfortunately we don't seem to.
```
We need to add baseline jobs for kselftest kernels as it seems some of them just fail to boot.

@mgalka what's your opinion on that?

**Comment by nuclearcat** [comment]
@gctucker do you think it is feasible to test kselftest kernels on baseline too?
It will add load to labs, but seems it might be useful, as some kselftest kernels was not bootable.
Right now we have them excluded from baseline tests:
```
    filters:
      - blocklist: *kselftest_defconfig_filter
```

**Comment by gctucker** [comment]
Yes, and I think baseline-nfs would make more sense with kselftest.  Maybe both would be useful actually.  I'm just not entirely sure any more why this filter was created, I see in the git history that it was inherited from the original boot tests.  Most likely, kselftest kernels were only built and not used at all at the time so it's worth trying to enable that now.

Note: Ideally, I think baseline on kselftest kernels should only be run in labs that also have kselftest enabled.  But that's more something for the new pipeline syntax (which doesn't exist yet) where we could define dependencies between tests.  So kselftest tests would only run if the baseline test with the kselftest kernel passed.  It should be useful preparation work to just enable baseline on kselftest everywhere for now.

**Comment by nuclearcat** [comment]
Fixed by https://github.com/kernelci/kernelci-core/pull/1606
