### ISSUE TITLE
Zombie infestation on one(or more) of jenkins runners

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1499]
```
Tasks: 5738 total,  68 running, 531 sleeping,   0 stopped, 5046 zombie
```
Some sources say this might happen because Mr Jenkins docker processes dont have init, so it start to spawn zombies.
At one hand we plan to say eventually bye-bye to Mr Jenkins, but how many mondays(and other days) we will have to deal with Mr Jenkins zombies overflowing from runner, who ruining our morning coffee?

References to sources:
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
(It seems also Docker now _have_ embedded even special micro-init just for that https://github.com/krallin/tini.)
As [stackoverflow](https://stackoverflow.com/questions/49162358/docker-init-zombies-why-does-it-matter) suggests:
**tini is pretty minimal overhead and widely used, so why not use --init most of the time?**

**Comment by nuclearcat** [comment]
Possible problem solution explained in https://issues.jenkins.io/browse/JENKINS-45888

**Comment by gctucker** [comment]
Does the cleanup script get rid of them during the weekly production update?

**Comment by nuclearcat** [comment]
I noticed amount of zombie processes reach thousands just after few hours of production update. This might be possible reason also why we get production "stuck" often after update.

**Comment by nuclearcat** [comment]
I checked only after complete production update, when builders are rebooted. 
Didn't checked yet state of zombies when script is run and for example jenkins are paused.

**Comment by gctucker** [comment]
Sounds like something to double check on Monday during the next prod update then I guess.

My point is that if the zombie pods get deleted once a week then it's not a real problem.  We already know things are a bit broken with the Jenkins / Kubernetes communication but that's going away.  It's still useful to understand why this is happening in case we start seeing it as well with the new pipeline.

**Comment by nuclearcat** [comment]
I just monitored now, when no jobs are running on production, zombie processes are disappearing.

I suspect when jenkins are fully loaded, zombie processes generated by jobs (if theory is correct, it is happening on containers without init process) exceed some limits and might cause jenkins runner to hang and other anomalies
```
Nov 08 13:25:04 kernelci6 systemd-udevd[1583]: Failed to fork: Resource temporarily unavailable
Nov 08 14:56:19 kernelci6 dockerd[1322]: time="2022-11-08T14:56:19.434273577Z" level=error msg="Error sending stop (signal 15) to container" container=697ab30faae0d451ec126d94cb179fd9f707723c13e246bcd0810b68f99b03fb error="Cannot kill container 697ab30faae0d451ec126d94cb179fd9f707723c13e246bcd0810b68f99b03fb: unknown error after kill: fork/exec /usr/bin/runc: resource temporarily unavailable: <nil>: unknown"
```

**Comment by gctucker** [comment]
OK, so we might just need to reduce the number of executors in Jenkins if that's spawning too many builds.
