### ISSUE TITLE
ChromeOS builds storage need cleanup too

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1521]
It seems we have missing cleanup for ChromeOS storage too, AFAIK results already are stored limited time, so it makes sense to limit builds storage too.

/home/kernelci/cleanup.sh /data/storage.chromeos.kernelci.org/kernelci/chromeos-stable +24

**Comment by nuclearcat** [comment]
I think we need to go a bit in-depth, as some of the kernels/images we are using for flashing and rootfs images also have different expiration policy. 
@gctucker i think we need to make /data/storage.chromeos.kernelci.org/images as exception, like we did with cip. Is that right?
Maybe we can move flashing kernel to /data/storage.chromeos.kernelci.org/images as well, to not make too many exceptions.
If correct, i will proceed with PR.

**Comment by VinceHillier** [comment]
/home/kernelci/cleanup.sh contains an exception for images by default, we can override that to include the kernels in the service with:

`ExecStart=/home/kernelci/cleanup.sh /data/storage.chromeos.kernelci.org +14 images\\|stable`

**Comment by nuclearcat** [comment]
I checked file list in configs, it looks like we need exception only for **images** directory. Stable need to be cleaned up as others.
Everything else looks good to me, maybe for start we can backup "stab'e" directory, if it is not too large, and after i will do one more build of ChromiumOS, if everything ok, we remove backup as well.

**Comment by gctucker** [comment]
There's already a backup in Azure, created automatically.

**Comment by VinceHillier** [comment]
The following has been performed in production:

1)  Commissioned a new 500G azure volume for chromeos builds.  @nuclearcat the original directory is located here `/data/storage.chromeos.kernelci.org-datamount-deleteme-after-chromeos-build`.  I'll delete this once you confirm everything is good.  

The new volume received an rsync of the original directory and is mounted at `/data/storage.chromeos.kernelci.org`.

2) Timer setup for chromeos cleanup.  It currently runs at 00:05 daily and prunes all directories (except `images`) older than +14.  This has already ran today so the data on the mount has already been pruned.

**Comment by VinceHillier** [comment]
@nuclearcat I've deleted the old directory.

Closing this.
