### ISSUE TITLE
all kselftest results is not being parsed

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1607]
```
/lava-8569803/0/tests/1_kselftest-tpm2
./kselftest.sh: 131: ./parse-output.py: not found
+ ../../utils/send-to-lava.sh ./output/result.txt
```
As result it is unable to report failures/regressions.

**Comment by nuclearcat** [comment]
Example:
https://storage.kernelci.org/mainline/master/v6.2-rc2-10-g69b41ac87e4a/arm64/defconfig/gcc-10/lab-broonie/kselftest-futex-sun50i-a64-pine64-plus.html

**Comment by nuclearcat** [comment]
This is likely breaking commit: https://github.com/kernelci/test-definitions/commit/65be76866f2d09e6871fe37bf1e668680cdd7630

**Comment by gctucker** [comment]
What's more worrying is how this didn't get spotted on staging or with the pipe cleaner job during the production update.  I guess we can revert test-definitions to last week's version for now?

cc @mgalka
