### ISSUE TITLE
ChromiumOS image integration & publishing workflow

### ISSUE THREAD

**Issue by 10ne1** [kernelci/kernelci-core#1657]
Hi! I would like to document the steps I'm doing to create ChromiumOS images for integration into KernelCI for tasks such as #1608 or #1610 as well as some guidance on how to manage the tech debt (some upstream divergence is required, how to minimize it and so on).

This is mostly a brain dump based on what I'm currently doing, please feel free to suggest improvements.

### Part 1: Build and validate the image **outside** KernelCI.

This part is about doing any necessary local development to  ensure an image can boot the system and produce relevant results for the kernel community, avoid potential licensing issues, ensure kernels are not tainted during boot and so on.

1. Ensure you are familiar with the [ChromiumOS build docs and processes](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_guide.md).
2. Clone the [KernelCI ChromiumOS manifest](https://github.com/kernelci/kernelci-core/tree/chromeos/config/rootfs/chromiumos) and use the manifest to fetch the same source versions used by KernelCI.
3. Do a local unmodified build for the target board and fix any issues. KernelCI might not yet be building/validating an image for your target and so the build might be already broken for various reasons.
4. Look at the [release dash](https://chromiumdash.appspot.com/home), the [issue tracker](https://partnerissuetracker.corp.google.com/u/1/issues?q=componentid:931982) and [Gerrit code review](https://chromium-review.googlesource.com), they might contain known issues or fixes for a specific version used by KernelCI or for a specific SoC/board. Compare with upstream ChromiumOS mainline development branches which might contain fixes. Backport if necessary.
5. Some bugs might be real upstream ChromiumOS bugs, please report these together with any workarounds on the respective [issue tracker](https://partnerissuetracker.corp.google.com/u/1/issues?q=componentid:931982) component. If you have fixes you can upstream them (see Part 3).
6. Modify the local sources so no proprietary components or third-party licensing agreements are required. This might include in-kernel firmware, drivers, proprietary OpenGL implementations, third-party libraries and so on.
7. Components removed at the previous step will likely need replacing to ensure a functioning system, for e.g. mesa might be required to replace a proprietary OpenGL implementation. Other components might need modifications to function with the replacement, for example the minigbm library might need modifications to work with an upstream driver alternative like panfrost. Work with others to find suitable replacements and document them (for e.g. what is the minimum required upstream kernel driver/device-tree or mesa version?).
8. Boot and ensure the system is still functional. Run some local tests if you have the board or flash a lab device with the new image and run remote tests. Verify ChromeUI still works and Tast tests can run.
9. Make sure to keep track of and document all modifications done in Part 1. These are required for part 2.

### Part 2: Integrate into KernelCI and publish the new images.

The following steps are for integrating the work done in Part 1 into KernelCI and have the builders automatically build via `kci_rootfs` then publish the images.

1. Add all changes done in part 1 to the [existing KernelCI manifest](https://github.com/kernelci/kernelci-core/tree/chromeos/config/rootfs/chromiumos) repositories or create new "forks" and add them to the manifest, if they do not yet exist. Please be careful to only fork when absolutely necessary, to minimize divergence. Forked repositories must be public.
2. Modify the kernelci-core [rootfs build configs](https://github.com/kernelci/kernelci-core/blob/chromeos/config/core/rootfs-configs-chromeos.yaml) and the [build script](https://github.com/kernelci/kernelci-core/blob/chromeos/config/rootfs/chromiumos/scripts/build_board.sh) to allow for building the new image.
3. Setup the kernelci-core build container and run a local build start-to-finish via `kci_rootfs`. [Here](https://github.com/nuclearcat/kernelci-quickstart-scripts/blob/main/5-build-cros-rootfs.sh) is an example how to do it.
4. Fetch the kci_rootfs built artifacts and flash the image (locally or remote), re-validate the testing.
6. Create a Changelog file containing all the changes from the previously published image (if it exists), as well as divergences from mainline ChromeOS, known problems, backported fixes and so on.
5. Post a Github PR, address review feedback and land the changes in kernelci-core.
7. Proceed to update all devices of the same type in production with the new image.
8. Publish the image and Changelog, create a public anouncement with some instructions how to flash the image or build it from scratch from the kernelci-core repo. These instructions might be a separate INSTALL file in addition to the Changelog.

### Part 3: Send changes upstream to ChromiumOS.

This part is about minimizing the divergence between KernelCI and upstream ChromiumOS builds. Ideally there should be no divergence, but considering the KernelCI project is focused more on testing mainline / -next / other dev kernel versions, some amount of divergence is unavoidable.

1. Ensure you are familiar with the [Contributors Guide](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/contributing.md) and are added to the ChromiumOS CLA (details in the guide) so you can contribute upstream, otherwise Gerrit will auto-reject your proposed changes.
2. Rebase the changes done in parts 1 and 2, which are upstreaming candidates, onto a mainline ChromiumOS dev branch build. The [dev guide](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_guide.md) contains details on how to set up a dev build.
3. Build and test the image from the rebased branches.
4. Open issuses on the  [bug tracker](https://partnerissuetracker.corp.google.com/u/1/issues?q=componentid:931982) for the components you want to upstream into. Clearly describe the problem and your use case, any workarounds or if you already have a fix.
5. Add the issue number to the commit message via `BUG=` tags and the testing you've done (`TEST=` tags).
6. Post the Gerrit CL for review, identify the code owners (see the `OWNERS` file in each SDK component) and explicitly ask for review by adding them to the CL.
7. Once the changes land in upstream CrOS, take note which release versions will contain them and drop the downstream patches upgrading ChromeOS in KernelC, or remove the forks if there are no more downstream patches. Don't forget to also update the images Changelog.

### Part 4: Establishing a reference kernel to ship inside images.

Normally KernelCI will build and test its own kernel versions with the ChromiumOS images, depending on the specific test cases and branches, however a static/non-changing kernel must be shipped inside the image as part of the ChromiumOS SDK build process, to ensure a functional system after flashing the image on a device.

In the **ideal situation**,  this kernel should be an upstream stable release without any downstream patches, however not all SoCs, chipsets or boards are supported entirely in the upstream kernel, so certain trade-offs must be made including sometimes maybe using downstream ChromiumOS "vendor" kernels if no upstream variants exists.

To give a concrete example of such a trade-off, the MT8192 and MT8183 SoCs are relatively well supported by the upstream kernel and are already tested in KernelCI (e.g. baseline tests). With around a total of a dozen small patches, backported from `linux-next` or from soon-to-be-upstreamed OOT patches, to get  display, sound and GPU acceleration in good shape (example patches [here](https://gitlab.collabora.com/aratiu/linux-public/-/commits/dev/kernelci/R106-15054.B)), we can get a functioning system on a 6.2 upstream kernel, without conflicts.

When newer ChromiumOS images are released, we can upgrade the reference kernels and drop the upstreamed patches, reaching the ideal situation. Obviously this is harder if the SoC/board is not supported in the upstream kernel in the first place, but that is a separate problem, in which case the ChromiumOS image might be stuck on older reference kernels.

**Comment by gctucker** [comment]
Thanks!  I guess the next steps are to create some issues about things that need to be done and this guide should be added to the ChromeOS instance documentation on https://kernelci.org/docs/instances/chromeos/.  But that's not necessarily something for you to take care of.  Some reviews would be welcome though.
