### ISSUE TITLE
Commit 46976d4df cause k8s to restart pods with bugs indefinitely

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1677]
Commit: https://github.com/kernelci/kernelci-core/commit/46976d4df272d2d16edfda80fdf57e44f72b9e52

While originally commit was intended to prevent jobs continuing in case of error, it caused unexpected, opposite result, when kubernetes pod program (shell script) return non-zero code, pod will consider it as crash and will try to restart.
Another negative result, that job in jenkins will not show error, since job is still trying to run, but rather return timeout, making troubleshooting of bugs difficult.

For example:
```
build-j61810-x86-64-gcc-10-x86-64-defconfig-crypto-vmds9          0/1     CrashLoopBackOff   19 (2m28s ago)   92m
pod log:
```
Upload path: kernelci/staging-stable/staging-stable-20230125.0/x86_64/x86_64_defconfig+crypto/gcc-10
400 Client Error: Provided JSON is not valid for url: https://api.staging.kernelci.org/build
'kernel' is a required property
 
Failed validating 'required' in schema['properties']['artifacts']:
    {'patternProperties': {'.*': {'items': {'properties': {'contents': {'items': {'type': 'string'},
                                                                        'type': 'array'},
                                                           'key': {'type': 'string'},
                                                           'path': {'type': 'string'},
                                                           'type': {'enum': ['file',
                                                                             'directory',
                                                                             'tarball'],
                                                                    'type': 'string'}},
                                            'required': ['type',
                                                         'path'],
                                            'type': 'object'},
                                  'type': 'array'}},
     'required': ['kernel'],
     'type': 'object'}
 
On instance['artifacts']:
    {u'config': [{u'key': u'config',
                  u'path': u'config/kernel.config',
                  u'type': u'file'},
                 {u'key': u'fragment',
                  u'path': u'config/kernelci.config',
                  u'type': u'file'},
                 {u'key': u'log',
                  u'path': u'logs/config.log',
                  u'type': u'file'}]}
```

**Comment by nuclearcat** [comment]
After discussion we have two approaches to solve this:
1)Revert commit
2)Change Kubernetes job policy to not restart pod on failure

@broonie maybe you have any ideas? 
I might make temporary patch to revert PR, so staging jobs with errors will not case indefinite loops

**Comment by gctucker** [comment]
The root cause for the kernel build error is that cross-compile strings are populated with `null` in `bmeta.json`:
https://storage.staging.kernelci.org/kernelci/staging-stable/staging-stable-20230125.0/x86_64/x86_64_defconfig+crypto/gcc-10/bmeta.json
```json
    "environment": {
        "arch": "x86_64",
        "compiler": "gcc",
        "compiler_version": "10",
        "compiler_version_full": "gcc (Debian 10.2.1-6) 10.2.1 20210110",
        "cross_compile": null,
        "cross_compile_compat": null,
```
which then leads to this error:
```
make[1]: Entering directory '/tmp/kci/linux/build'
  GEN     Makefile
scripts/Kconfig.include:39: compiler 'Nonegcc' not found
```

In production, they are set to empty strings:
https://storage.kernelci.org/mainline/master/v6.2-rc5/x86_64/x86_64_defconfig/gcc-10/bmeta.json
```json
    "environment": {
        "arch": "x86_64",
        "compiler": "gcc",
        "compiler_version": "10",
        "compiler_version_full": "gcc (Debian 10.2.1-6) 10.2.1 20210110",
        "cross_compile": "",
        "cross_compile_compat": "",
```

I've reproduced this locally so investigating what caused this, something in the build config rework presumably.

**Comment by gctucker** [comment]
Also worth mentioning, this is only happening within `merge_configs.sh`.

**Comment by gctucker** [comment]
(so builds that don't use fragments should not be impacted)

**Comment by gctucker** [comment]
OK I've added a fix for this on #1664 :
```diff
diff --git a/kernelci/build.py b/kernelci/build.py
index 5b4e1b19e..c52d3f119 100644
--- a/kernelci/build.py
+++ b/kernelci/build.py
@@ -961,7 +961,7 @@ class EnvironmentData(Step):
 
         build_env, arch = (opts[key] for key in keys)
         cross_compile, cross_compile_compat = (
-            build_env.get_arch_param(arch, param)
+            build_env.get_arch_param(arch, param) or ''
             for param in ('cross_compile', 'cross_compile_compat')
         )
         cc = build_env.cc
```
and verified this locally.

**Comment by gctucker** [comment]
So now the issue should go away with the next staging builds.  Still it would be good to determine what's the best way to make Kubernetes kernel build jobs abort as soon as a build step fails without getting the pod into an infinite loop.

**Comment by nuclearcat** [comment]
Issue solved
