### ISSUE TITLE
Rework cros-* Dockerfiles to config/docker

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1718]
The ChromeOS Docker images still have their Dockerfiles in `config/docker-old`.  They now need to be reworked and moved to `config/docker` so they can be built with the `kci_docker` tool.

Original issue: #1335

**Comment by nuclearcat** [comment]
I think all cros-* docker files already moved, as i know

**Comment by gctucker** [comment]
No it's still in `docker-old` on today's `main` branch:
```
$ git show --oneline | head -1
836a5b0b6b57 kernelci.cli.node: set --limit default to 10
$ ls config/docker-old
build-and-push.sh  cros-qemu-modules  cros-sdk  cros-tast
```
