### ISSUE TITLE
Refactor "lab" related configuration and logic

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-core#1725]
Entities known as "labs" in KernelCI Pipeline are not exactly what the name could suggest. They are actually runtime environment for test jobs like shell or kubernetes. 

* Code should be refactored to change naming of these entities from `lab` to 'runtime environment`.
* Runtime environment handling logic should be moved from Runner service to separate classes responsible for that.

- [x] https://github.com/kernelci/kernelci-core/issues/1726
- [x] https://github.com/kernelci/kernelci-core/issues/1729
- [x] https://github.com/kernelci/kernelci-pipeline/issues/207

**Comment by gctucker** [comment]
All related PRs have been merged.

Some on-going work is still needed to gradually adjust the new Runtime class for the new use-cases but I think that's beyond the scope of this issue which was about putting things in place for this to evolve hand-in-hand with the rest of the pipeline.
