### ISSUE TITLE
Add libkeyutils to build-base image, or disable building sample(s)

### ISSUE THREAD

**Issue by ihalip** [kernelci/kernelci-core#187]
It looks like linux-next now needs libkeyutils to build some recently added sample code:
https://storage.kernelci.org/next/master/next-20190918/x86_64/allmodconfig/gcc-8/build.log

Either `libkeyutils` needs to be added to the build-base image, or kernel should be built with `CONFIG_SAMPLE=n`/`CONFIG_SAMPLE_WATCH_QUEUE=n`.

**Comment by gctucker** [comment]
The error is:

```
  HOSTCC  samples/watch_queue/watch_test
/usr/bin/ld: cannot find -lkeyutils
collect2: error: ld returned 1 exit status
make[3]: *** [scripts/Makefile.host:107: samples/watch_queue/watch_test] Error 1
```

**Comment by ihalip** [comment]
Still happens in the latest linux-next:
https://storage.kernelci.org/next/master/next-20190924/arm/allmodconfig/gcc-8/build.log

**Comment by gctucker** [comment]
@ihalip Nothing has been done so far to address this problem, so it's still broken as expected.

**Comment by gctucker** [comment]
OK I think I'll be able to take a look at this next week.

**Comment by gctucker** [comment]
@ihalip It looks like this issue can't be reproduced with next-20191014, see the log here:
https://storage.kernelci.org/next/master/next-20191014/arm/allmodconfig/gcc-8/build.log

**Comment by gctucker** [comment]
And I see that the patch to add `samples/watch_queue` doesn't need that lib any more, this line has been removed from the patch:
```
HOSTLDLIBS_watch_test += -lkeyutils
```
So, I guess this isn't needed any more.  I haven't found the email discussing this part of the patch though.

**Comment by ihalip** [comment]
Didn't find an e-mail either, I guess it was just temporary in Dave's tree as he progressed on the `KEY_NOTIFICATIONS` feature. I see that indeed this is not failing in recent linux-next builds, so this issue can be closed.
