### ISSUE TITLE
Add stable-next branch builds

### ISSUE THREAD

**Issue by sashalevin** [kernelci/kernelci-core#191]
Hello,

Could we please add a new branch for -stable testing? it's a subset of -next of stable tagged commits.

Here's the diff:
```
diff --git a/build-configs.yaml b/build-configs.yaml
index b6f347b..b0359f9 100644
--- a/build-configs.yaml
+++ b/build-configs.yaml
@@ -100,6 +100,9 @@ trees:
   samsung:
     url: "https://git.kernel.org/pub/scm/linux/kernel/git/kgene/linux-samsung.git"
 
+  sasha:
+    url: "https://git.kernel.org/pub/scm/linux/kernel/git/sashal/linux-stable.git"
+
   soc:
     url: "https://git.kernel.org/pub/scm/linux/kernel/git/soc/soc.git"
 
@@ -794,6 +797,11 @@ build_configs:
     branch: 'linux-5.2.y'
     variants: *stable_variants
 
+  stable_next:
+    tree: sasha
+    branch: 'stable-next'
+    variants: *stable_variants
+
   tegra:
     tree: tegra
     branch: 'for-next'
```

**Comment by gctucker** [comment]
@sashalevin See #194 - I've tweaked a few things with the names, to call your tree `sashal` and follow the "tree_branch" naming convention for the build config entry.

Next bit of information is who to send the email reports to.  Should it be you and the regular KernelCI reports list, and maybe the stable list as well?  Please list the recipients you want here and I'll add them to the PR.

**Comment by sashalevin** [comment]
@gctucker Maybe let's just start with me and the regular list, and give it a few weeks to see how it looks like?

**Comment by gctucker** [comment]
@sashalevin Sure, I've added that to the PR.

**Comment by gctucker** [comment]
PR merged, it's all working as expected.
