### ISSUE TITLE
Convert kernelci.conf to TOML

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1913]
The current settings file e.g. `kernelci.conf` uses the old `configparser` module.  It would be good to transition to TOML with the `toml` module as that's a better defined format for handling settings and should be fairly backwards-compatible.

It would also fix some issues with argument types as the `kernelci.conf` format assumes all values are strings, so arguments that are meant to be integers don't work as expected.  With TOML, strings have to be in quotes like in JSON so it's clearer.

The only issue with this is for users who rely on a `kernelci.conf` settings file, I guess we would need to add support for TOML and keep the `configparser` implementation with a deprecation period.  This could probably be done easily just by checking the file name e.g. `.config` or `.toml`.

**Comment by gctucker** [comment]
@JenySadadia Maybe we could use dotted keys in the section names rather than `:`?  That would require a bit more rework but it could have some advantages, relying more on the TOML standard than special implementation in the KernelCI code.

Documentation: https://toml.io/en/v1.0.0#keys

**Comment by JenySadadia** [comment]
> @JenySadadia Maybe we could use dotted keys in the section names rather than `:`? That would require a bit more rework but it could have some advantages, relying more on the TOML standard than special implementation in the KernelCI code.
> 
> Documentation: https://toml.io/en/v1.0.0#keys

Dotted keys will be confusing when we have dotted values.
e.g. we have `db:staging.kernelci.org`.

The parser will assume it is a nested dictionary and parse it accordingly.
```
[db.staging.kernelci.org]
test = 2
> 'db': {'staging': {'kernelci': {'org': {'test': 2}}}}
```
In this case, we will still need to use the double quotes around the value:
```
[db."staging.kernelci.org"]
test = 2
> 'db': {'staging.kernelci.org': {'test': 2}}
```
I'd suggest keeping keys as is with `:` or else it will be more confusing for a user to decide when to use double quotes.

**Comment by gctucker** [comment]
OK, I think we should be sending an email to the list about the added support for TOML and maybe mention this point to see what users think.  TOML is a widely used language and clearly documented so I think users might already be used to this kind of thing.  It's all about the tradeoff between user-friendliness and code sustainability, using built-in TOML features such as dotted keys is better from a design point-of-view.

**Comment by JenySadadia** [comment]
> OK, I think we should be sending an email to the list about the added support for TOML and maybe mention this point to see what users think. TOML is a widely used language and clearly documented so I think users might already be used to this kind of thing. It's all about the tradeoff between user-friendliness and code sustainability, using built-in TOML features such as dotted keys is better from a design point-of-view.

OK. I'll send an email for further discussion.

**Comment by gctucker** [comment]
Great.  Also the timeline for deprecation isn't all finalised now but I think it would make sense to include this as part as the transition to the new API so probably we can already say the .conf format is going to be supported at least until the end of 2023.

**Comment by JenySadadia** [comment]
Sent out an [email](https://lore.kernel.org/kernelci/0d91ed78-e648-d41e-1f29-2eb7dbb488ae@collabora.com/T/#u) to the mailing list for further discussion.

**Comment by nfraprado** [comment]
The documentation still uses the `.conf` for the examples (eg. https://kernelci.org/docs/core/kci_build/). Maybe updating those should also be tracked by this issue?

**Comment by JenySadadia** [comment]
> The documentation still uses the `.conf` for the examples (eg. https://kernelci.org/docs/core/kci_build/). Maybe updating those should also be tracked by this issue?

Thank you for pointing it out @nfraprado 
Since this issue is specific to the implementation, I'll add a separate issue for the documentation.

**Comment by JenySadadia** [comment]
> The documentation still uses the `.conf` for the examples (eg. https://kernelci.org/docs/core/kci_build/). Maybe updating those should also be tracked by this issue?

Please see https://github.com/kernelci/kernelci-core/issues/1999

**Comment by JenySadadia** [comment]
> Sent out an [email](https://lore.kernel.org/kernelci/0d91ed78-e648-d41e-1f29-2eb7dbb488ae@collabora.com/T/#u) to the mailing list for further discussion.

Following the discussion, I have created a follow-up PR https://github.com/kernelci/kernelci-core/pull/2033 with the dotted key syntax.

**Comment by JenySadadia** [comment]
Closing this issue as https://github.com/kernelci/kernelci-core/pull/2033 has been merged.
