### ISSUE TITLE
Add `kci user` command for user profiles

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-core#2016]
Add command to `kci user` tool to find user profiles matching provided attributes.

- [ ] Implement API binding for kernelci-api endpoint `/users/profile` to `kernelci/api/latest.py`
- [ ] Add `find_users` command to `kernelci/cli/users.py`

**Comment by gctucker** [comment]
What's the difference between finding users and "user profiles"?

**Comment by JenySadadia** [comment]
> What's the difference between finding users and "user profiles"?

`find_users` is the `kci user` command to get user profiles.

**Comment by gctucker** [comment]
Ah you mean `kci user find`?  Like we have for nodes?  Basically that's to find users, which might happen to have a UserProfile model in the database, but from a CLI usage pov it's all users right?

**Comment by JenySadadia** [comment]
> Ah you mean `kci user find`? Like we have for nodes? Basically that's to find users, which might happen to have a UserProfile model in the database, but from a CLI usage pov it's all users right?

Yes, that's true.
