### ISSUE TITLE
Add kernel thermal group testing branch

### ISSUE THREAD

**Issue by dlezcano** [kernelci/kernelci-core#202]
Hi all,

is it possible to add the kernel thermal group tree:
  https://git.kernel.org/pub/scm/linux/kernel/git/thermal/linux.git  thermal/testing

Given the feature request #23 I'm not sure the branch name above is valid. If that is the case I'll renamel it 'testing'

Thanks in advance
  -- Daniel

**Comment by gctucker** [comment]
I'm actually making a fix for that, as we've seen other issues with `/` characters.  But if it's easy for you to rename the branch then yes please, it would seem a safe thing to do.

There are a couple of things we need to know regarding the extra workload this would add to the builders.  I would like to make a Github issue template for other people who want to add a branch, so here's a draft:

- How much build coverage do you need for your branch?

Generally speaking, it's a good rule to build fewer variants for branches that are further away from mainline and closer to individual developers to scale better and be able to add more branches.  This can be fine-tuned with arbitrary filters, but essentially there are 3 main options:

1. build everything, including allmodconfig, which amounts to about 220 builds, like we do with linux-next
2. skip a few things such as allmodconfig as it's very long to build and can't be booted, and also architectures that are less useful such as MIPS which saves 80 builds and doesn't have much test platforms in KernelCI, like we do with the media subsystem tree
3. build only the main defconfig for each architecture to save a lot of build power, get the fastest results and highest boots/builds ratio like we do with the gpio substem tree

- How often do you expect this branch to be updated?

KernelCI monitors each branch once every hour and builds it every time it finds a new revision.  If you push once a week or less, it's easier to allow for many build variants as this reduces the build load on average.  Conversely, if you push several times every day then a small set of builds should be used.

It's also possible to increase the build capacity if needed but this comes with a cost.  Avoiding unnecessary builds is always a good way to reduce turnaround time and not waste resources.

**Comment by dlezcano** [comment]
How much build coverage do you need for your branch?
  -> Option 3
How often do you expect this branch to be updated?
  -> Should be updated several times per week

**Comment by gctucker** [comment]
Thanks, see PR #204.

**Comment by gctucker** [comment]
PR merged, it's all working as expected.
