### ISSUE TITLE
Errors on kci commands references in Early Access guide

### ISSUE THREAD

**Issue by laura-nao** [kernelci/kernelci-core#2158]
I'm following the [Setting up the kci tool](https://kernelci.org/docs/api/early-access/#setting-up-the-kci-tool) section of the Early Access guide using the latest `kernelci/kernelci` Docker image.

The `kci api hello` and `kci user` commands referenced in the guide return the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/kci", line 4, in <module>
    __import__('pkg_resources').run_script('kernelci==1.1', 'kci')
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/EGG-INFO/scripts/kci", line 20, in <module>
    from kernelci.cli import Args, kci
ModuleNotFoundError: No module named 'kernelci.cli'
```

**Comment by gctucker** [comment]
Thanks for reporting this, I'll take a look today.

**Comment by gctucker** [comment]
All the fixes in the code and documentation are now in PRs.  Hopefully this can be reviewed and merged on Monday.  I think we'll have to merge and deploy it anyway even if it's not formally reviewed as this really needs to be fixed.

**Comment by gctucker** [comment]
OK all the fixes have been merged now, only the documentation page update is still pending.  It would be good to go through these instructions a bit later today when the `kernelci/staging-kernelci` Docker image has been rebuilt to double check it's all working as expected.

**Comment by gctucker** [comment]
Now this is actually complete, and the production update is scheduled to happen today.  So leaving this issue closed :)
