### ISSUE TITLE
Add branch queue/6.6 and linux-6.6.y from stable-rc tree

### ISSUE THREAD

**Issue by crazoes** [kernelci/kernelci-core#2254]
Which Git branch do you want to add?
⇨ Git repo URL:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/

⇨ Git branch name:
queue/6.6 and linux-6.6.y

How much build coverage do you need for your branch?
As other stable-rc branches.

**Comment by nuclearcat** [comment]
Merged to production
