### ISSUE TITLE
Adding jobid field in node

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2311]
During node creation, we have the following workflow now:

1) Allocate node, retrieve node ID (hexadecimal string).
2) Create job template (depends on the runtime, e.g., LAVA template or k8s template). Most likely, the job name and certain parameters will use the Node ID (this is why we need to retrieve it in step 1).
3) After job completion, we receive a callback that will set the Node to "done" and set relevant fields to results (add artifacts, etc.).

We need to add an intermediate step between 2 and 3, where after submitting the job we get the identifier of the job in the runtime. In the case of LAVA, it is a numerical job ID; in the case of k8s, it is the job name and so on. We then update the node with this identifier.
This identifier will be used to retrieve job status and results.

The job ID will likely be set at the node as "data.jobid".

**Comment by pawiecz** [comment]
> In the case of LAVA, it is a numerical job ID;

For reference: LAVA TestJob ID is [assigned on submission](https://github.com/kernelci/kernelci-pipeline/blob/2b1a0fbb10d4861c19eb94a30f10b2ebd4641b26/src/scheduler.py#L85) (`get_job_id()` on this object is just [casting it to int](https://github.com/kernelci/kernelci-core/blob/2e3c36a8adfcdb0603e026631f9b3416d1116e46/kernelci/runtime/lava.py#L192))

**Comment by nuclearcat** [comment]
I think we need to assume/cast it to string, as for kubernetes and docker it will be string.
Just later, if we work with LAVA (polling for example) we can cast it back.

**Comment by JenySadadia** [comment]
Thanks for the pointers @pawiecz @nuclearcat
