### ISSUE TITLE
Add recipes for `kci docker` to build API/Pipeline images

### ISSUE THREAD

**Issue by pawiecz** [kernelci/kernelci-core#2330]
Production deployment of API/Pipeline services could benefit from having tagged Docker container images. Currently they are built on-demand from `docker-compose` configuration.

Although tagged images could be produced from these recipes, unifying image creation process with `kci docker` templates could simplify this process in the long run.

Images to convert (repo: image):

- [ ] #2331
- [ ] api: kernelci/api-ssh image (?)
- [x] #2350
- [ ] pipeline: kernelci/lava-callback
- [ ] pipeline: kernelci/kcidb (?)

**Comment by nuclearcat** [comment]
I think this one completed too?
