### ISSUE TITLE
Please remove non-working builds from android-3.18

### ISSUE THREAD

**Issue by lag-linaro** [kernelci/kernelci-core#235]
None of the builds below are supported. Please prevent them from being initiated.

allnoconfig ‐ arc
bigsur_defconfig ‐ mips
fpga_defconfig ‐ arc
fpga_noramfs_defconfig ‐ arc
nlm_xlr_defconfig ‐ mips
sb1250_swarm_defconfig ‐ mips
sead3micro_defconfig ‐ mips
tinyconfig ‐ arc

**Comment by lag-linaro** [comment]
Please. :smiley:

**Comment by lag-linaro** [comment]
These non-legitimate builds are still failing.

Please could someone either remove them, or show me how.

**Comment by gctucker** [comment]
I wonder if `lee_android_3.18` is still being used.

**Comment by nuclearcat** [comment]
Didn't noticed that, i will check who is author and will ask

**Comment by lag-linaro** [comment]
You can strip out all of my `*android_3.18` builds, thanks.

**Comment by gctucker** [comment]
> You can strip out all of my `*android_3.18` builds, thanks.

Ah OK, thanks for confirming.
