### ISSUE TITLE
Please enable allmodconfig builds for ARMv7

### ISSUE THREAD

**Issue by lag-linaro** [kernelci/kernelci-core#237]
I hear that they are missing due to legacy issues which should no longer be a problem.

**Comment by gctucker** [comment]
We're already building allmodconfig for arm, here's an example from linux-next master branch:
https://kernelci.org/build/id/5dc52a4659b5149d5a138e10/

**Comment by lag-linaro** [comment]
Could you enable them on android-3.18 please?

https://kernelci.org/build/android/branch/android-3.18/kernel/ASB-2019-11-05_3.18-46-g7d43891e8a90/

**Comment by lag-linaro** [comment]
Does https://github.com/kernelci/kernelci-core/pull/240 do the right thing?

**Comment by gctucker** [comment]
Yes, here's a quick way to check:
```
$ ./kci_build list_kernel_configs --kdir=linux --config=lee_android_3.18 | grep allmodconfig
x86_64 allmodconfig gcc-8
arm64 allmodconfig gcc-8
arm allmodconfig gcc-8
```

**Comment by gctucker** [comment]
The PR has been merged so this resolved now.

**Comment by lag-linaro** [comment]
Great, thank you @gctucker

**Comment by gctucker** [comment]
And this should be rolled out in production tomorrow.

**Comment by lag-linaro** [comment]
Ideal, thanks again.

What about #234 and #235? Will they make it too?

**Comment by gctucker** [comment]
Sorry I won't have the time to deal with those, maybe someone at Linaro can make a PR?

**Comment by lag-linaro** [comment]
I would do it myself, but they do not look straight forward.

I do not thing anyone from Linaro works on this anymore.

**Comment by lag-linaro** [comment]
Okay I think I fixed one of them: https://github.com/kernelci/kernelci-core/pull/245

However, I do not see any current examples of other branches blacklisting configs.

Could you either implement it or point me in the right direction please?

**Comment by gctucker** [comment]
@lag-linaro FYI it built fine: https://kernelci.org/build/id/5dce98c659b5141c56cf54bf/

**Comment by lag-linaro** [comment]
Great. Thanks. :)
