### ISSUE TITLE
Shutdown ChromeBooks properly

### ISSUE THREAD

**Issue by a-wai** [kernelci/kernelci-core#2492]
Currently, we issue the `poweroff` command at the end of a test job. This results in the following output:

```
System has not been booted with systemd as init system (PID 1). Can't operate.
```

Moreover, this is only executed when tests run successfully, meaning there are many occurrences where we simply cut the power to the device. This could lead to filesystem corruption and consequently trigger issues like #2491.

We should instead ensure we issue the appropriate command, and always do so.

**Comment by a-wai** [comment]
See #2497 & #2498 for details, but basically the issue with the systemd message was that the command was pretty much `ssh sync && poweroff`, with `sync` being executed on the ChromeBook through `ssh`, but `poweroff` was executed on the LAVA runner, inside the test container (which obviously can't work).

The LAVA jobs linked in the comments for those PRs show devices properly shutting down, so I think this issue can be closed once those are merged :)

**Comment by a-wai** [comment]
A good example of a corrupt device likely due to a hard reboot is [dell-latitude-5400-4305U-sarien-cbg-0](https://lava.collabora.dev/scheduler/device/dell-latitude-5400-4305U-sarien-cbg-0):
* job [13357222](https://lava.collabora.dev/scheduler/job/13357222) runs perfectly fine
* DUT likely crashed during job [13357236](https://lava.collabora.dev/scheduler/job/13357236) and was forced off when the job timed out
* [13357275](https://lava.collabora.dev/scheduler/job/13357275) exhibits the sign of a corrupt filesystem

This case will be more complex to handle though, as we can't really prevent devices from crashing while running the tests...

**Comment by nuclearcat** [comment]
Sarien issue plaguing me since long time, maybe we need to report to google that. It is abnormal, that system get corrupted due crash.

**Comment by a-wai** [comment]
> For eg. I'm not entirely certain [this job pointed by Arnaud](https://lava.collabora.dev/scheduler/job/13357236) has a crash according to the CrOS definition of a crash [...]. In this specific case, maybe the kernel experienced a hang / hard lock-up...

It seems so (kernel hang) based on the kernel logs, my choice of words was indeed sub-optimal.

**Comment by a-wai** [comment]
> Sarien issue plaguing me since long time

"Fun" fact regarding the devices I re-flashed last week: those are **all** (yes, all!) devices from the following types:
* `sarien` (including `arcada`, all Dell devices, Intel chip)
* `grunt` (Acer and multiple HP models, AMD chip)
* `zork` (Lenovo and multiple HP models, AMD chip)
* `hatch` (Asus, Intel chip)

There's very likely a problem with those device types making them more likely to FS corruption.

For other device types, there are a few MTK affected (3x `corsola`, 2x `asurada`, 2x `cherry`), and only 1x of both `skyrim` and `trogdor`. The latter can be considered rare incidents, and MTK devices should be monitored until we have more stats.

**Comment by a-wai** [comment]
Interestingly, it seems no `asus-CM1400CXA-dalboz` (which are actually `zork` device types) is affected; however, those weren't used by the new system until today (see https://github.com/kernelci/kernelci-pipeline/pull/541), so let's see how it goes now...

**Comment by a-wai** [comment]
Closing as the templates were reworked to send `poweroff` to the DUT after the tests ran.
