### ISSUE TITLE
Allowing filtering on tree/branch pairs

### ISSUE THREAD

**Issue by a-wai** [kernelci/kernelci-core#2548]
Currently, our `rules` system allows one to ensure jobs will run only for allowed values of each specified node attribute.

This makes it possible to run jobs only for a given set of trees and/or branches, but doesn't allow to enter a list of tree/branch combinations, which can be useful to have more fine-grained conditions.

An example situation could be the following:
* the `mainline` tree is built on branch `master`
* the `media` tree is built on branches `master` and `fixes`
* we want to run a job on both `mainline/master` and `media/fixes`, but not on `media/master`

This could be achieved by allowing `tree` and `branch` rules to be formatted as `<tree>/<branch>` and process those entries in a special way if they contain a `/` character. This solution feels the most user-friendly one, however implementing this might be quite complex.

Alternative solutions could be:
* add a new `build_config` rule type, which will look at the build configs defined in the pipeline configuration to identify the tree/branch combinations, and then proceed to checking the corresponding node attributes
*  add a new rule type (name TBD) which will be a special case (just like current `*_version` rules) in the filtering code working as described above (accept entries in the `<tree>/<branch>` format and filter based on the node's tree and branch)

**Comment by nuclearcat** [comment]
Proper planning is actually is major part of the job.

**Comment by JenySadadia** [comment]
This new filter is worth mentioning here https://github.com/kernelci/kernelci-pipeline/blob/main/doc/developer-documentation.md?plain=1#L78.

**Comment by nuclearcat** [comment]
I will take care about that today

**Comment by JenySadadia** [comment]
> I will take care about that today

Okay, thanks.
