### ISSUE TITLE
Need a way to set the job timeout per job

### ISSUE THREAD

**Issue by a-wai** [kernelci/kernelci-core#2576]
In the legacy system, we could set the job timeout for each test case.

This is no longer the case as there was no urgent need to implement it so far. However, codec-related Tast tests on ChromeBooks can now take a huge amount of time:
* a bit less than 1 hour on [jacuzzi](https://lava.collabora.dev/scheduler/job/14182221)
* almost 2 hours on [cherry](https://lava.collabora.dev/scheduler/job/14204661)

This is way over our default 30 minutes timeout, which otherwise work fine for most jobs.

As a consequence, we should reinstate the ability to set different timeout values as job params.

Note: the 30 minutes timeout is currently hardcoded in both the [base LAVA template](https://github.com/kernelci/kernelci-core/blob/main/config/runtime/base/lava.jinja2#L38) (global job timeout) and the [tast tests template](https://github.com/kernelci/kernelci-core/blob/main/config/runtime/tests/tast.jinja2#L6) (test timeout); custom job timeouts should therefore affect both those definitions (and likely other test templates as well, for completeness).

**Comment by a-wai** [comment]
Also noteworthy: both the [v4l2-decoder-conformance](https://github.com/kernelci/kernelci-core/blob/main/config/runtime/tests/v4l2-decoder-conformance.jinja2#L15) and [kselftest](https://github.com/kernelci/kernelci-core/blob/main/config/runtime/tests/kselftest.jinja2#L3) templates already use such a parameter.

However, the global job timeout set in the base LAVA template isn't affected, as the values used so far for `job_timeout` have always been <= 30min.

**Comment by broonie** [comment]
This will also be important for tests that are expected to run quickly, especially with baseline tests where things like boot failures will be seen - keeping boards occupied needlessly really hurts availability and throughput.
