### ISSUE TITLE
 test-configs.yaml: Enable additional preempt-rt tests #2397 

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2643]
This is continuation of discussion in https://github.com/kernelci/kernelci-core/pull/2397
I am converting to the issue, so i can reduce amount of pending PR, to reduce load on staging scripts.

**Comment by musamaanjum** [comment]
I'd created the same issue some weeks ago: https://github.com/kernelci/kernelci-project/issues/417

There is no plan to work on it yet.

**Comment by musamaanjum** [comment]
Closing this task as discussion about enabling more tests is located at: https://github.com/kernelci/kernelci-project/issues/417
