### ISSUE TITLE
Extending usage of "submitter" field

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2654]
The "submitter" field in nodes was initially intended to track who submitted the node (using a token hash). However, as we've remodeled the API implementation for developer interactions, this field may have more uses.

The submitter field is typically created in the checkout node and then propagated through the node tree by inheriting the parent's value. In rare cases (e.g., test retries), the submitter field might be changed.

Currently, we set it by default as a workaround in the API:

```python
@app.post('/node', response_model=Node, response_model_by_alias=False)
... skipped some code ...
        node.submitter = "service:pipeline"
```

We need to submit node data properly from checkout. I suggest the following:

1) During normal operation, when checkout creates the first node, set it to "service:pipeline".
2) For pipeline API (maintainer functions for custom checkout, test job retry, and patchset), set it to "user:userid:hash". Here, "user" is a static value, "userid" could be a username or email, and "hash" is a randomly generated hexadecimal string. This should be set for both the checkout node AND the job retry node. We'll retrieve the userid from the JWT token.
3) The kcidb bridge service will forward to kcidb only nodes that have the submitter field set to "service:pipeline" for now (this is likely to change soon if we ensure kcidb can handle manual submit entries).

This approach will help resolve the following issues:
- Avoid polluting kcidb with custom checkouts (non-tip-of-tree) and job retries that might skew statistics.
- Assist in tracking custom submissions by maintainers (the hash allows submitters to use it as a keyword to track nodes belonging to their submission).

Steps required for implementation:

- [x] Implement submitter field in the pipeline checkout service
- [x] Implement functionality to ignore all nodes with a submitter that is not "service:pipeline"
- [x] Implement submitter field in pipeline API for custom checkout tree and return the created node with submitter field to the user
- [x] Modify API code to emit an error and require the submitter field to be set on checkout nodes, instead of setting a default value if missing. Also, verify that all other nodes are sent with the submitter field

**Comment by JenySadadia** [comment]
Hello @nuclearcat 
Thanks for creating the issue and the detailed explanations.

Here are some thoughts on it:
- I lost track of why we added `submitter` field to the `Node`. `Node.owner` field was already there to identify submitter by its username.
>  Avoid polluting kcidb with custom checkouts (non-tip-of-tree) and job retries that might skew statistics.
- I believe one use case for extending `submitter` field is to avoid submitting data to KCIDB if the submitter is not staging pipeline. This is already in place as we are filtering events by `owner`. See https://github.com/kernelci/kernelci-api/blob/main/api/pubsub.py#L150. So the bridge service will only receive node events of its ownership.
> Assist in tracking custom submissions by maintainers (the hash allows submitters to use it as a keyword to track nodes belonging to their submission).
- I believe `Node.owner` information will be there to identify the owner for the below use case.

**Comment by nuclearcat** [comment]
> I lost track of why we added `submitter` field to the `Node`. `Node.owner` field was already there to identify submitter by its username. Could you please help me understand it?

As pipeline services operate under single username, at some moment we need to submit data from kernel maintainers and need way to be able to distinct it from data originated by pipeline services itself.



> I believe one use case for extending `submitter` field is to avoid submitting data to KCIDB if the submitter is not staging pipeline. This is already in place as we are filtering events by `owner`. See https://github.com/kernelci/kernelci-api/blob/main/api/pubsub.py#L150. So the bridge service will only receive node events of its ownership.

Custom checkout node, job retry - is submitted under same owner as pipeline services, otherwise pipeline services will ignore this node.

> I believe `Node.owner` information will be there to identify the owner for the below use case.
Node.owner is used only if we have multiple pipeline instances using same API instance, so they dont interfere with each other. It was theoretical possibility, but in reality nobody used this functionality yet.

**Comment by JenySadadia** [comment]
> > I lost track of why we added `submitter` field to the `Node`. `Node.owner` field was already there to identify submitter by its username. Could you please help me understand it?
> 
> As pipeline services operate under single username, at some moment we need to submit data from kernel maintainers and need way to be able to distinct it from data originated by pipeline services itself.
> 
> > I believe one use case for extending `submitter` field is to avoid submitting data to KCIDB if the submitter is not staging pipeline. This is already in place as we are filtering events by `owner`. See https://github.com/kernelci/kernelci-api/blob/main/api/pubsub.py#L150. So the bridge service will only receive node events of its ownership.
> 
> Custom checkout node, job retry - is submitted under same owner as pipeline services, otherwise pipeline services will ignore this node.
> 
> > I believe `Node.owner` information will be there to identify the owner for the below use case.
> 
> Node.owner is used only if we have multiple pipeline instances using same API instance, so they dont interfere with each other. It was theoretical possibility, but in reality nobody used this functionality yet.

Okay. Thanks a lot for explaining.
I think the better approach would be to implement user groups and permissions. And then we can use individual user accounts for all the submitters/maintainers to submit data. Add those users to a group and tell the staging pipeline to process them.

**Comment by JenySadadia** [comment]
> Okay. Thanks a lot for explaining. I think the better approach would be to implement user groups and permissions. And then we can use individual user accounts for all the submitters/maintainers to submit data. Add those users to a group and tell the staging pipeline to process them.

As per the discussion with @nuclearcat , we would proceed with `submitter` field for time being and will see if we can change that approach after LPC.

**Comment by JenySadadia** [comment]
Related PRs:
- https://github.com/kernelci/kernelci-pipeline/pull/778
- https://github.com/kernelci/kernelci-api/pull/546

**Comment by nuclearcat** [comment]
I believe it is completed and can be closed?

**Comment by JenySadadia** [comment]
Yes, this can be closed.
