### ISSUE TITLE
No Android 3.18 test builds for 2 days

### ISSUE THREAD

**Issue by lag-linaro** [kernelci/kernelci-core#312]
For some reason KernelCI hasn't picked up any new pushes from the `android-3.18` test branch for 2 days.

https://kernelci.org/job/lee/branch/android-3.18-preview/

Any idea why this is?

Usually the lag time is 'only' a few hours (assumingly this is polled, rather than triggered?).

**Comment by broonie** [comment]
We're experiencing serious stability problems with the Jenkins master and have disabled a lot of builds of trees that aren't mainline focused in order to reduce load on it and avoid triggering the issues, yours unfortunately got caught up in this.

We're in the process of redeploying to new instances which should address the capacity issues but unfortunately the Jenkins master is one of the last bits to be moved over.

**Comment by lag-linaro** [comment]
It's a shame since I have made KernelCI a critical piece of my workflow.

Without it I'm forced to push backports to `android-3.18` lacking full testing exposure.

FYI: `android-3.18` is consumed by *real/deployed* devices.

Stable is as important as Mainline in this regard.

Any way this branch can be 'turned back on'?

**Comment by lag-linaro** [comment]
Seems to be working well again.  Thank you.

Closing this for now.

**Comment by gctucker** [comment]
@lag-linaro Well it may seem to be working again, but the issue I described in my previous comment still hasn't been resolved.  I guess we can move the discussion to emails.

**Comment by lag-linaro** [comment]
Happy to chat via email.

I've messaged you in the past, but received no reply.

**Comment by lag-linaro** [comment]
Something else going on?  I've only had 1 build this week.

This really does stop me in my tracks.

**Comment by gctucker** [comment]
Yes, lots going on with moving servers around in production.  The builds were not paused for that long though, so maybe you've been unlucky with the timing somehow.  It should all be back on track now, sorry for the inconvenience.

**Comment by lag-linaro** [comment]
I'll try to push another SHA.

Not sure when the window was, but my builds from late Tuesday and all day yesterday were ignored.

**Comment by gctucker** [comment]
It looks like there are also some issues with some Jenkins servers, taking a look.  That deserves a separate issue though, this one was initially about the 3.18 branch being disabled but it's resolved now as all branches are being monitored.

**Comment by lag-linaro** [comment]
I didn't want to keep cluttering up your repo with new Issues every time this happens.

Thanks for reporting back though.  It makes me feel a bit better that you've found the cause.

**Comment by gctucker** [comment]
For quick questions, can also get in touch using the #kernelci IRC channel on Freenode.

**Comment by lag-linaro** [comment]
Wonderful.  Will do.
