### ISSUE TITLE
Clang support

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#319]
The mainline Linux kernel can now be built with both GCC and LLVM/Clang, at least for some architectures such as `arm64`.  The initial aim for KernelCI is to be able to support multiple compilers in general, and to ensure that Clang kernel builds are working as expected.

Objectives:
- [x] `build-configs.yaml` and `kci_build` support for multiple compilers to produce kernel builds
- [x] backend database schema updated to support multiple compilers
- [x] email reports updated to show the compiler used in builds and test results
- [x] frontend web dashboard updated to show the compiler used in builds and test results
- [x] enable lld #104
- [x] fix extra config options support (fragments...) #136

**Comment by gctucker** [comment]
Clang support is now all operational in production.  Regular updates are still needed to bring in new LLVM versions, but that's regular maintenance.

**Comment by nickdesaulniers** [comment]
My sincere gratitude to the KernelCI developers and all of work went in to getting to this milestone.  With proper CI in place, we can develop more assuredly!
