### ISSUE TITLE
Python 2.7 to be deprecated next year

### ISSUE THREAD

**Issue by chaws** [kernelci/kernelci-core#33]
Today after updating pip2, i got the message

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7

Just FYI

**Comment by gctucker** [comment]
There's a milestone now to cover all the tasks related to Python 3: https://github.com/kernelci/kernelci-core/milestone/2
