### ISSUE TITLE
KUnit

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#332]
[KUnit](https://www.kernel.org/doc/html/latest/dev-tools/kunit/index.html) provides unit tests from the Linux kernel source tree.  As such, it is an obvious test suite to run on kernelci.org.

The challenges are that unit tests aren't typically run on a target platform different than the one where the kernel was built, since they are essentially platform-independent tests.  They should however be tested with at least one 32-bit and one 64-bit architecture to provide complete coverage.

- [ ] KUnit coverage with standard UML builds
- [ ] KUnit coverage with x86_64
- [ ] Kunit coverage with a 32-bit architecture
- [ ] Rust for Linux coverage included in KUnit coverage

**Comment by Heidifahim** [comment]
First fully functional revision of kunit integration kernelci command line (kci_build) here: https://github.com/Heidifahim/kernelci-core/tree/kci_kunit

Need to have:
1) Make sure to be using the latest upstream [linux-kseltest](git://git.kernel.org/pub/scm/linux/kernel/git/shuah/linux-kselftest.git) tree which has all KUnit changes merged. 
2) Need to apply this [JSON patch ](https://patchwork.kernel.org/patch/11458861/) for it to function (this should be upstream soon as well).

Usage: 
1) to run ALL kunit tests written in linux tree:
```./kci_build` build_kernel --defconfig=defconfig --arch=x86 --build-env=gcc-8 --kdir=$HOME/workspace1/linux --kunit=alltests --kunit_json=out.json```

2) to run a set of default KUnit tests found at `linux/arch/um/configs/kunit_defconfig: `
```./kci_build` build_kernel --defconfig=defconfig --arch=x86 --build-env=gcc-8 --kdir=$HOME/workspace1/linux --kunit --kunit_json=out.json```

3) To run your own specified KUnit tests, create a `kunitconfig` file under `linux/` and run: 
```./kci_build` build_kernel --defconfig=defconfig --arch=x86 --build-env=gcc-8 --kdir=$HOME/workspace1/linux --kunit --kunit_json=hello.json```

Now currently trying to implement kunit integration within "kci_test submit" command instead.

**Comment by gctucker** [comment]
Thanks @Heidifahim for the update, that's great progress.  I think it's now all down to reshaping the code to better fit the current scheme of things, which can be done one step at a time.

The first step I guess would be to have the ability to generate a command and run it locally, as an implementation of the `LabAPI` class.  I guess the first step would be to generate the command to run with template parameters (the `.generate()` method) and then run it (the `.submit()` method).  Initially this can be done synchronously, just by calling `subprocess.call()` or something similar.

**Comment by gctucker** [comment]
We've now been running KUnit tests using the new API on x86_64, here's some sample logs:
https://storage.staging.kernelci.org/api/kunit-64c0d4cd53f14b471c8037b5/?C=M&O=D

There's also a plain run based on UML but we've had issues with it.  I'll keep posting updates as things evolve around this topic.
