### ISSUE TITLE
kci_build: pass tokens other than via cmdline

### ISSUE THREAD

**Issue by khilman** [kernelci/kernelci-core#369]
When using kci_build from CI/automation environments (e.g. jenkins/gitlab/k8s), it's useful to see the kci_build commands in the logs for debug purposes.  However, the need to pass the token on the command-line can make it complicated to be sure that it doesn't show up in the logs.

e.g. for jenkins you can configure secrets, and jenkins can hide these secrets in the log.  But if you're building containers with kci_build commands to run in Kubernetes, you it's more difficult to hide the commandline from the output logs (or container environment descriptions)

**Comment by gctucker** [comment]
Yes, it has always been clear that having a config file for secrets and other settings that don't change with each job should be stored in a config file.  I guess it's becoming higher priority now with Kubernetes.  Sounds like something to resume working on next week.

**Comment by gctucker** [comment]
Support for a settings file was adding a while ago, see the documentation: https://kernelci.org/docs/core/settings/
