### ISSUE TITLE
Use kernelci Python package in Docker images on staging

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#401]
As a follow-up task from #400, to start using this on staging.kernelci.org:
- [x] #1320
- [x] update the `kernelci/build-base` Docker image to install the `kernelci` package from the git repo
- [x] update `kernelci-deploy` tools to rebuild the Docker images used on staging with a layer for the `kernelci` Python package

**Comment by gctucker** [comment]
Moving to Phase 2 as there were on-going discussions around how to handle the common code.

**Comment by gctucker** [comment]
Dropping from 2020-Q3 plan as while this is a nice thing to have it's not a high enough priority one.  Other refactoring would need to be done to make this truly useful, i.e. to have the YAML config files also in the Docker image.

**Comment by nuclearcat** [comment]
I think it is done with introduction of kci_docker?

**Comment by gctucker** [comment]
> I think it is done with introduction of kci_docker?

Yes,
