### ISSUE TITLE
Please upgrade QEMU/kvm firmware images to latest EDK2 stable tag

### ISSUE THREAD

**Issue by ardbiesheuvel** [kernelci/kernelci-core#423]
Linux recently introduced a new protocol for loading the initrd from UEFI firmware, and QEMU has been updated to take advantage of it. Subsequently, the old method of passing it via the command line has been deprecated, which means that kernel configs may decide to disable it.

Since QEMU supports the new protocol, we should switch to it, not only for testing coverage but also because it will be the only method that is guaranteed to be available going forward.

Therefore, please upgrade all firmware images used for QEMU EFI boot to versions that are built from EDK2 git tag 'edk2-stable202005' (this applies to i386, x86_64, ARM and arm64)

**Comment by gctucker** [comment]
The current UEFI binaries<sup>[1]</sup> were supplied to us and we just had to install them on the storage server.  This was the preferred way to ensure they were built according to your expectations.

See the original commit from @roxell before we copied the binaries to the storage server: https://github.com/roxell/kernelci-core/commit/5282995a6abcc50c826826c0e8ffae131eb4b805
and the meeting minutes: https://groups.io/g/kernelci/message/480

Are there new binaries for `edk2-stable202005` available anywhere?  If not, would you prefer to make them for us again or provide some instructions to have them made by KernelCI?

[1] https://storage.kernelci.org/images/uefi/111bbcf87621/

**Comment by ardbiesheuvel** [comment]
If I remember that discussion correctly, you insisted on me providing instructions so you could build your own binaries. 

I can build the binaries for you, or provide instructions again, whichever you prefer.

**Comment by ardbiesheuvel** [comment]
Prebuilt binaries can be found here:
https://people.linaro.org/~ard.biesheuvel/qemu-efi-stable202005.tgz

**Comment by gctucker** [comment]
Thanks!  I'll upload that to the storage server and make a PR to start using them.

Build instructions are really important to be able to reproduce the builds but especially so that anyone looking into the results can find out what is actually being used in the tests.  The meta-data provided with the binaries was good enough in this respect last time.

**Comment by gctucker** [comment]
I've unpacked the new binaries here:
https://storage.kernelci.org/images/uefi/edk2-stable202005/

@ardbiesheuvel What about the "mixed" 32/64 build for x86?  The current binaries include this one:
https://storage.kernelci.org/images/uefi/111bbcf87621/OVMF.fd-IA32X64-RELEASE-111bbcf87621

**Comment by ardbiesheuvel** [comment]
We don't need that one, all we need is a 32-bit and a 32-bit version, so we can test

32-bit firmware booting the 32-bit kernel
64-bit firmware booting the 64-bit kernel
32-bit firmware booting the 64-bit kernel

where the latter is what we typically refer to as 'mixed mode'

The IA32X64 one is a 64-bit firmware, but with 32-bit startup code. This is an internal detail, and entirely irrelevant to boot testing EFI kernels.

**Comment by gctucker** [comment]
OK so we'll just drop the `baseline-uefi_x86-mixed` test config variant.

**Comment by ardbiesheuvel** [comment]
We only need two different builds, i386 and x86_64, but there are still 3 different tests to be run: perhaps that simply means there are two different 64-bit qemu platforms: one with 32-bit firmware and 64-bit firmware.

**Comment by gctucker** [comment]
I see - then the "mixed" one will be an x86_64 QEMU booting with 32-bit UEFI.  I'll updated the PR accordingly.

**Comment by gctucker** [comment]
@ardbiesheuvel Last time, we had a `readme.txt` file explaining where the binaries came from:
https://storage.kernelci.org/images/uefi/111bbcf87621/readme.txt

Could you please provide us with some text here and we'll copy it to a file on the storage server in a similar way for this set of binaries?

**Comment by ardbiesheuvel** [comment]
On Wed, 15 Jul 2020 at 00:07, Guillaume Tucker <notifications@github.com>
wrote:

> @ardbiesheuvel <https://github.com/ardbiesheuvel> Last time, we had a
> readme.txt file explaining where the binaries came from:
> https://storage.kernelci.org/images/uefi/111bbcf87621/readme.txt
>
> Could you please provide us with some text here and we'll copy it to a
> file on the storage server in a similar way for this set of binaries?
>
>
>
No change there except for the commit id, which is the 202005 stable tag in
this case.

**Comment by gctucker** [comment]
OK thanks, I've created this file accordingly:
https://storage.kernelci.org/images/uefi/edk2-stable202005/readme.txt
```
origin:   https://github.com/tianocore/edk2
revision: edk2-stable202005

Images built under Debian Buster amd64 using the packaged GCC 8.3 toolchains,
x96_64-linux-gnu, aarch64-linux-gnu and arm-linux-gnueabihf and the GCC5
toolchain profile in EDK2.

iasl from acpica-tools 20181213.
```
