### ISSUE TITLE
spinning down clang-9 builds?

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#488]
With https://lore.kernel.org/lkml/20200902225911.209899-1-ndesaulniers@google.com/T/#t, we're looking to just support the latest given release of Clang, which is currently clang-10.  This means we can probably spin down clang-9 tests.  It might not yet be worthwhile to delete the docker images if we end up adding branches of stable to testing, but it's probably ok.

**Comment by gctucker** [comment]
Yes, we now need to drop clang-9 as v10.0.1 or above is required for building linux-next.  See #496.

However, should we start building some stable branches with clang-9 or is nobody building product kernels with Clang yet?

**Comment by gctucker** [comment]
As discussed, there is no need to start building stable branches with clang-9 so it can just be dropped.
