### ISSUE TITLE
Add branch for-kernelci from robh

### ISSUE THREAD

**Issue by robherring** [kernelci/kernelci-core#502]
Each git kernel branch is monitored every hour by kernelci.org.  Whenever a new
revision is detected, it will be built for a number of combinations of
architectures, defconfigs and compilers.  Then a build report will be sent,
some tests will be run and test reports will also be sent.

Please provide the information described below in order to add a new branch to
kernelci.org:

- **Which Git branch do you want to add?**

⇨ Git repo URL: git://git.kernel.org/pub/scm/linux/kernel/git/robh/linux.git

⇨ Git branch name: for-kernelci

- **How much build coverage do you need for your branch?**

Generally speaking, a good rule is to build fewer variants for branches that
are "further" away from mainline and closer to individual developers.  This can
be fine-tuned with arbitrary filters, but essentially there are 3 main options:

1. Build everything, including allmodconfig, which amounts to about 220 builds.
This is we do with linux-next.

2. Skip a few things such as allmodconfig as it's very long to build and
doesn't really boot, and also architectures that are less useful such as MIPS
which saves 80 builds and doesn't have many test platforms in KernelCI.  This
is we do with some subsystems such as linux-media.

3. Build only the main defconfig for each architecture to save a lot of build
power, get the fastest results and highest boots/builds ratio.  This is what do
with some maintainer branches such as linusw' GPIO branch.

⇨ Build coverage choice: 3 (Just arm and arm64 really)

- **How often do you expect this branch to be updated?**

If you push once a week or less, it's easier to allow for many build variants
as this reduces the build load on average.  Conversely, if you push several
times every day then a small set of builds should be used.

It's also possible to increase the build capacity if needed but this comes with
a cost.  Avoiding unnecessary builds is always a good way to reduce turnaround
time and not waste resources.

⇨ Estimated frequency: 1-2 times a week, but not every week

- **Who should the email reports be sent to?**

Standard email reports inlude builds and basic tests that are run on all
platforms. Please provide a list of email recipients for these.  Typical ones
are the regular KernelCI reports list, kernel mailing lists associated with the
changes going into the branch and related maintainers.

⇨ Recipients: robh@kernel.org

**Comment by gctucker** [comment]
@robherring There isn't any `for-kernelci` branch in your tree:
https://git.kernel.org/pub/scm/linux/kernel/git/robh/linux.git/refs/heads

It's not a big deal, but I would prefer to wait for the branch to be there and be able to test the config in PR #508 before merging it and deploying it on kernelci.org.

**Comment by robherring** [comment]
@gctucker It's there now.

**Comment by gctucker** [comment]
Thanks, looking fine: https://staging.kernelci.org/job/robh/branch/for-kernelci/

**Comment by gctucker** [comment]
@robherring OK it should be deployed in production tomorrow.

By the way, you might want to keep an eye on #396 as this is now about 75% complete.  It will probably land around the end of the year.  I guess we should run it on your for-kernelci branch when it's ready, and send you the email reports for it?

**Comment by robherring** [comment]
@gctucker Thanks!

I'm glad to see that. My current plan with for-kernelci branch is actually for PCI related testing. DT schema can be effectively tested on linux-next as lots of stuff doesn't go in via my branch (and I *usually* don't have breakage on my own branch). But maybe I'll be able to kill the gitlab-ci jobs I have.

**Comment by robherring** [comment]
@gctucker Why doesn't lab-nxp run my branch?

**Comment by gctucker** [comment]
@robherring There seems to be occasional errors with the NXP test lab API, causing some kernel revisions to not be tested there.  See this stable-rc revision didn't get NXP jobs either:
https://kernelci.org/test/job/stable-rc/branch/queue%2F5.4/kernel/v5.4.68-385-ga376a9ad881c/plan/baseline/

but the revision before that on the same branch did:
https://kernelci.org/test/job/stable-rc/branch/queue%2F5.4/kernel/v5.4.67-43-ged5b61efca0b/plan/baseline/

For each sampled revision, the KernelCI pipeline retrieves the list of all online devices from all the labs once before starting to schedule tests for them.  If the query to get that info from a lab failed (with a few retries), it won't get any jobs run.  I think this is most likely to be due to a timeout, if the lab server load is unusually high for some reason.
