### ISSUE TITLE
clang builds of mainline

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#518]
IIRC, we only ever turned on clang coverage for linux-next.  We should add builds of mainline with clang.

**Comment by gctucker** [comment]
Presumably we would want to build mainline with clang-10, and linux-next with clang-11?

Do we want to build the same set of arch/configs on mainline as on linux-next?

Maybe linux-next could gradually start extending its build coverage if new arches or config variants get supported with clang, and mainline would be building a smaller set of known supported ones.
