### ISSUE TITLE
arc clang builds not being run

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#592]
It looks like ARCH=arc builds are listed in [build-configs.yaml](https://github.com/kernelci/kernelci-core/blob/4303b606624bfba3ad347c9833e17feccd8f37aa/build-configs.yaml#L212-L213), but the frontend doesn't have results for such builds (ex. https://kernelci.org/build/next/branch/master/kernel/next-20210125/).  Is there a backend failure causing the results to not be displayed, or some other issue?

**Comment by nickdesaulniers** [comment]
cc @nathanchance (I didn't think we could build ARCH=arc, but TBH I've never tried. @gctucker mentioned it worked for him).

**Comment by gctucker** [comment]
Well I *think* it worked when the config was first merged since normally we only merge things that work, but maybe that was just an oversight.  In any case, we're not getting any results at the moment so something's probably a bit broken somewhere.  I'll start some local arc builds with the same Docker containers and see what happens.

**Comment by gctucker** [comment]
Erm no it blows up pretty early in the build:
```
  UPD     include/config/kernel.release
  UPD     include/generated/utsrelease.h
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/devicetable-offsets.s
clang: error: unknown argument: '-mmedium-calls'
clang: error: unknown argument: '-fsection-anchors'
clang: error: unknown argument: '-mlock'
clang: error: unknown argument: '-mswape'
clang: error: unknown argument: '-mno-sdata'
clang: error: unknown argument: '-fcall-used-gp'
make[2]: *** [../scripts/Makefile.build:117: scripts/mod/devicetable-offsets.s] Error 1
make[2]: *** Waiting for unfinished jobs....
clang: error: unknown argument: '-mmedium-calls'
clang: error: unknown argument: '-fsection-anchors'
clang: error: unknown argument: '-mlock'
clang: error: unknown argument: '-mswape'
clang: error: unknown argument: '-mno-sdata'
clang: error: unknown argument: '-fcall-used-gp'
make[2]: *** [../scripts/Makefile.build:279: scripts/mod/empty.o] Error 1
make[1]: *** [/root/kernelci-core/linux/Makefile:1205: prepare0] Error 2
make[1]: Leaving directory '/root/kernelci-core/linux/build-arc-clang-11'
make: *** [Makefile:185: __sub-make] Error 2
make: Leaving directory '/root/kernelci-core/linux'
Traceback (most recent call last):
  File "./kci_build", line 477, in <module>
    status = opts.command(configs, opts)
  File "./kci_build", line 340, in __call__
    install_res = self._install_step(step, args)
  File "./kci_build", line 353, in _install_step
    return step.install(args.verbose)
  File "/root/kernelci-core/kernelci/build.py", line 1020, in install
    kimages = self._find_kernel_images(image)
  File "/root/kernelci-core/kernelci/build.py", line 994, in _find_kernel_images
    files = set(os.listdir(path))
FileNotFoundError: [Errno 2] No such file or directory: 'linux/build-arc-clang-11/arch/arc/boot'
```
The generated `make` command was:
```
# make KBUILD_BUILD_USER=KernelCI ARCH=arc LLVM=1 CROSS_COMPILE=arc-elf32- CC="ccache clang" O=/root/kernelci-core/linux/build-arc-clang-11 -Clinux -j4 uImage
```
That doesn't yet explain why we're not seeing those errors in the build results, but now we need to decide whether we want that to be fixed or if we should just remove `arc` from the Clang builds.

What do you guys think?  If arc is on your roadmap, I should think it's worth at least fixing the KernelCI side of it and report the errors.

**Comment by nickdesaulniers** [comment]
I would remove it for now.
