### ISSUE TITLE
Hardware video codecs in Chrome OS

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#670]
Some embedded SoCs have hardware blocks to accelerate video decoding. This is about enabling some tests in KernelCI for them, at least on one type of hardware.

The Chrome OS tests for this can be found here:
https://chromium.googlesource.com/chromium/src/+/refs/heads/master/docs/media/gpu/video_decoder_test_usage.md

**Comment by nuclearcat** [comment]
I think in ChromeOS R106 we have tests video.PlatformDecoding.ffmpeg_vaapi* which all use acceleration api and we can achieve this issue by using them.
