### ISSUE TITLE
Upstream kunit implementation for unicode

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-core#675]
Test proposed by Gabriel Krisman.

**Comment by gctucker** [comment]
Is there a downstream implementation somewhere already?  Please provide a link and describe any known challenges with upstreaming it.

**Comment by krisman** [comment]
patches sent: https://lore.kernel.org/linux-fsdevel/20210531184742.1142042-1-krisman@collabora.com/T/#u

**Comment by gctucker** [comment]
We don't have KUnit completely enabled and automated in KernelCI, so we can't really test this on staging right now.  If other KUnit PRs would benefit from it then it would be a good reason to accelerate KUnit support during this sprint, but I don't think there are that many.  KUnit will ultimately be supported in KernelCI, it might just take a few more weeks.

**Comment by gctucker** [comment]
The patch has been sent and seems to be waiting to be applied.  Closing as nothing else will be done in the near future from a KernelCI point of view, first we need to enable KUnit tests to run and then we'll review the situation with actual coverage.
