### ISSUE TITLE
kselftest: Extend futex tests (private vs shared) 

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-core#677]
There is already a kselftest collection with futex tests, and it's being run by KernelCI on some platforms.  Here's an example:
https://staging.kernelci.org/test/plan/id/60acb891d8ebd9ffd3fe855c/

It needs to be extended as coverage is currently rather limited.  So we could be using a branch on the [KernelCI kernel tree](https://github.com/kernelci/linux) or patch files (`git format-patch`) to dynamically include them on top of the regular kernel builds run on staging.  There is already a process in place for this using [`kernelci-deploy`](https://github.com/kernelci/kernelci-deploy).

As seen in the example above, a large proportion of the test cases are skipped.  It would be worth investigating why this is the case, maybe some extra kernel config options need to be enabled or some issues with kselftest need to be fixed.

**Comment by gctucker** [comment]
Is this referring to the existing kselftest futex tests?  Those are already being run by KernelCI so expanding them would be pretty straightforward from an automation point of view:
https://linux.kernelci.org/test/plan/id/60aae9a0512521b02bb3af9a/

**Comment by andrealmeid** [comment]
Yes, it's referring to the current kselftests. The idea here is to expand the current test to cover more of the futex code, covering all the futex memory types:

- private futexes
- shared futexes (shmem/anon page)
- shared futexes (mmap/inode backed)

I've implemented this for futex2, so it should be trivial to port to original futex: https://gitlab.collabora.com/tonyk/linux/-/blob/futex2/tools/testing/selftests/futex/functional/futex2_wait.c

**Comment by andrealmeid** [comment]
I wrote a patch file for it, and I'll add to KernelCI's staging: 
[0001-selftests-futex-Create-futex-wait-tests.txt](https://github.com/kernelci/kernelci-core/files/6555778/0001-selftests-futex-Create-futex-wait-tests.txt)

(GitHub doesn't supports `.patch`, so that's why this is a `.txt.`)

**Comment by gctucker** [comment]
> I wrote a patch file for it, and I'll add to KernelCI's staging:
> [0001-selftests-futex-Create-futex-wait-tests.txt](https://github.com/kernelci/kernelci-core/files/6555778/0001-selftests-futex-Create-futex-wait-tests.txt)
> 
> (GitHub doesn't supports `.patch`, so that's why this is a `.txt.`)

I've added it to be deployed automatically on staging, it's going to be applied on top of linux-next:
https://github.com/kernelci/kernelci-deploy/commit/b2d3282b1eb50bb86c2ea4436cc66f9b2148446b

Normally there are 3 jobs on staging every day, once every 8h, and the rotate between mainline, stable 5.4 and next.  I'll probably change that to run more frequently during the sprint, and they can be triggered by hand at any time.  So I'm starting one with linux-next now.

**Comment by andrealmeid** [comment]
Patches sent upstream: https://lore.kernel.org/lkml/20210531165036.41468-1-andrealmeid@collabora.com/

**Comment by gctucker** [comment]
@andrealmeid This kernel revision on staging.kernelci.org includes your patch but the `futex_wait` results are not there:
https://staging.kernelci.org/test/plan/id/60b5ef116656975a96902fc9/

Kernel git history showing your patch being applied:
https://github.com/kernelci/linux/commits/staging-next

It could be because it needs to be added to the `run.sh` script:
https://github.com/kernelci/linux/blob/staging-next/tools/testing/selftests/futex/functional/run.sh#L67

**Comment by gctucker** [comment]
@andrealmeid However it does seem to be run according to the test log, but the result is `relative` which is not a valid keyword:
https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20210601.0/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-8/lab-collabora/kselftest-futex-asus-C523NA-A20057-coral.html#L2930

**Comment by andrealmeid** [comment]
@gctucker I added `futex_wait` to `run.sh` in the version sent to the mailing list. Should I open a PR to kernelci/kernelci-deploy updating it?

> @andrealmeid However it does seem to be run according to the test log, but the result is `relative` which is not a valid keyword:
> https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20210601.0/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-8/lab-collabora/kselftest-futex-asus-C523NA-A20057-coral.html#L2930

About this, this is being triggered by another test that I have written in the past and it's already upstream: https://github.com/kernelci/linux/commit/f4addd54b1617067f735ad194a3580a2db7b8bf5#diff-ee397ad534d30ab118627c413dd9fa88b6fffcf833d6feac5b6e5650b3c4f96c

I'm checking what's going on here

**Comment by gctucker** [comment]
@andrealmeid The kselftest patches still don't seem to have been merged.  Moving this to the main KernelCI board as it's now out of scope for the hackfest.

**Comment by andrealmeid** [comment]
@gctucker It was merged at TIP tree, so I think it's a matter of time to get to mainline: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=c3d128581f64a9b3729e697a63760ff0a2c4a8fe

**Comment by gctucker** [comment]
Thanks, that's great.  The tip tree is actually covered by KernelCI, so we could decide to enable this kselftest to be run.  For some reason it doesn't appear here, maybe it's just a configuration issue somewhere:
https://linux.kernelci.org/test/plan/id/60f7071b5ae3404d161160ac/

Closing this issue as the initial work has been done.
