### ISSUE TITLE
LTP: Add fanotify() tests

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-core#680]
This is about adding or improving LTP tests for [`fanotify()`](https://man7.org/linux/man-pages/man7/fanotify.7.html).  This would typically involve:

* enabling the LTP subset on staging.kernelci.org to run the `fanotify()` test on some designated platforms
* recreating rootfs images with LTP including any changes to the test to verify their results on staging.kernelci.org
* preparing for production deployment when LTP changes are merged, if any are required

**Comment by krisman** [comment]
Some support exists on LTP, according to Amir.  We want to verify it is ran, and extend if needed.

**Comment by gctucker** [comment]
Moving to hackfest 2 as an interesting topic to pick up.
