### ISSUE TITLE
kselftest: Soft-dirty Page Entry Bit

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-core#681]
- Recent regressions show need for this
  - Focus on TLB invalidation corner cases after cleaning a range
  - /proc/clear_refs

Proposed by @krisman

**Comment by gctucker** [comment]
@krisman It's unclear how this could be tested.  Is it possible to do it via user-space, with a test script or a C program?  Or, does it need direct kernel access in which case it would probably need to be part of kselftest?

Having links to mailing list discussions or fixes around regressions previously found would also help understand the kind of test needed to catch new ones in the future.

**Comment by krisman** [comment]
@gctucker it can be tested solely with a C program. no hardware or kernel level code needed.  I couldn't find any tests related to this on selftests.

Example of problem this would have caught: https://lore.kernel.org/linux-mm/20210127235347.1402-2-will@kernel.org/

**Comment by gctucker** [comment]
Could be kselftest

**Comment by krisman** [comment]
patches sent. https://lkml.org/lkml/2021/5/28/679

**Comment by gctucker** [comment]
Nice :)  Next week we could pick this patch for kernels build on staging and enable the `soft-dirty` collection to get it tested early.

**Comment by gctucker** [comment]
@krisman The kselftest patches were never applied, could you please follow up?

Moving this to the main KernelCI workboard as it's now out of scope for the hackfest.  When this lands in linux-next we may start enabling it in KernelCI.  We may also do that earlier by using the patch applied on kernels built on staging.kernelci.org.

**Comment by musamaanjum** [comment]
The patch has been sent: https://lore.kernel.org/lkml/20220224212335.3045905-1-usama.anjum@collabora.com/

**Comment by musamaanjum** [comment]
Patch has been accepted. I'll enable it in KernelCI once it reaches in linux-next.

**Comment by musamaanjum** [comment]
After a couple of more acceptance and rejections, the patch was accepted some days ago. The test is already in linux-next. The `soft-dirty` test was added in `selftest/vm` suite which is already enabled in KernelCI. So we can find the results of the soft-dirty test in KernelCI already: https://staging.kernelci.org/test/plan/id/626289c146e6d0c8bb1786a7/

**Comment by gctucker** [comment]
Fantastic
