### ISSUE TITLE
baseline: Extend cross-platform coverage

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-core#682]
Current `baseline` tests are very basic, just covering err, warns, bugs, boot login and bootrr in some platforms. While they need to complete within seconds, additional checks could be added to detect many other kinds of critical issues.  There are already platform-specific scripts, those could be extended but having more general tests that can be run on all platforms would be even better.  For example, when not all CPUs were brought up as see on this platform:

https://linux.kernelci.org/test/plan/id/60aaed77013458514db3afa8/
https://storage.kernelci.org/mainline/master/v5.13-rc3/arm64/defconfig/clang-10/lab-collabora/baseline-r8a77960-ulcb.html#L205

- [x] #701 check CPUs are all brought up successfully

**Comment by gctucker** [comment]
Closing now as the suggested topic to check CPUs has been resolved.
