### ISSUE TITLE
Clang builds

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#694]
Chrome OS kernels are built with a particular version of LLVM/Clang.  While KernelCI already builds kernels with regular versions of Clang, using the same compiler as on production devices could potentially extend coverage for such devices when building upstream kernels.

This issue is first about determining:
* Which versions of Clang to use
* Which kernel variants to build: CPU architecture, defconfig, extra fragments, branches... for each Clang version
* Which tests to run with the Clang builds
* Whether building kernels with GCC makes any sense for Chrome OS testing, given it's already covered on [linux.kernelci.org](https://linux.kernelci.org)?

- [x] #712 Support Chrome OS defconfigs
- [x] #713 cros defconfigs
- [x] #714 llvm-13

**Comment by ribalda** [comment]
#712 Will add the proper configuration for this build

**Comment by ribalda** [comment]
#714 will add the llvm version used in ChromeOS

**Comment by gctucker** [comment]
I've added the `native` label as the LLVM 13 builds can be enabled in the main instance of KernelCI since they're generic .deb packages rather than specific Chrome OS builds.

**Comment by gctucker** [comment]
All done, closing now.
