### ISSUE TITLE
Add a bootrr test to check all CPUs are brought up successfully

### ISSUE THREAD

**Issue by eballetbo** [kernelci/kernelci-core#701]
As part to extend cross-platform coverage #682 we would like to add more generic tests in bootrr. One new test could be to check that all CPUs are brought up successfully.  For example, this board only has the big cluster working and not the little one: https://linux.kernelci.org/test/plan/id/609092c1abc2cef5c6c917d0/ but it's not reported as an error because the kernel only prints warnings.

That test has only sense when CONFIG_SMP is set as is expected to fail if is not.

The first idea is to extend bootrr to add a shell script that can look at the dmesg for this kind of error.

https://github.com/kernelci/bootrr

- [ ] https://github.com/kernelci/bootrr/pull/11

**Comment by 10ne1** [comment]
I'll try to find a method other than parsing dmesg for the "failed to boot CPU" warning in case messages change between board platforms (or simply change in future kernels) and also ideally this test should be a generic one in bootrr .not board-specific :+1:

**Comment by gctucker** [comment]
Enabled in production, here's a sample test case result:
https://linux.kernelci.org/test/case/id/60d9f6948388a949be23bbdf/
