### ISSUE TITLE
LTP: Enable crypto tests to run

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#702]
The LTP crypto tests are almost all being skipped because kernel defconfigs don't enable crypto algorithms.  For example, on arm64:
https://linux.kernelci.org/test/plan/id/60af29fc28ce75881db3afac/

This could be improved by adding an LTP config fragment in [build-configs.yaml](https://github.com/kernelci/kernelci-core/blob/main/config/core/build-configs.yaml) with all the crypto algorithms enabled.

**Comment by metan-ucw** [comment]
Shouldn't we maintain the config fragments in upstream LTP repository instead? I remember that I talked about this with someone quite some time ago but nothing happened so far. If you need anything from the LTP upstream side I'm here and happy to help.

**Comment by crazoes** [comment]
@metan-ucw On grepping the LTP repo for CONFIG_ I found relevant results only in testcase readmes mentioning test relevant config options. What was the initially talked about plan about organization of the fragments in LTP? Also, even if we move fragments upstream in the LTP repo, current kernelci kernel config building logic only accepts and merges fragments from kdir/kernel/configs will need to update that logic(or change --kdir to use LTP repo path instead, although that seems a bit hacky) and will also need to start cloning LTP repo into the jenkins build environment.

**Comment by metan-ucw** [comment]
We talked on how to maintain config fragments in upstream LTP and so far we agreed on:

* The granularity of a fragment per directory with tests should be enough

* We should only add required config options, not the full tree that is enabled by a particular config option as the tree may not be stable between kernel versions

That should be good enough for a start.

**Comment by crazoes** [comment]
As discussed with @metan-ucw over ltp irc channel, this should be our long term plan to have support for automatically enabling the dependent config options. For now we will be proceeding with manually enabling them by adding it in fragments.
