### ISSUE TITLE
Show all test plans

### ISSUE THREAD

**Issue by pevik** [kernelci/kernelci-core#709]
I'd like to see all available test plans. Is there a link to show them and I just don't see it or it's missing?
Probably workaround is just to search in https://linux.kernelci.org/test/, but having a list under text "Plan" in https://linux.kernelci.org/test/plan/id/60af29fc28ce75881db3afac/, which would lead to page e.g. https://linux.kernelci.org/test/plans/ which lists them would be nice. 

Also it'd be nice if there were some details of the plan (maybe printed yaml described in https://kernelci.org/docs/tests/howto/?).

**Comment by gctucker** [comment]
There are several places where things can be found with a list of test plans, probably none of them is quite what you're looking for though.

First there's the YAML configuration where the test plans are actually defined:
https://github.com/kernelci/kernelci-core/blob/main/config/core/test-configs.yaml#L83

Then for each kernel revision you can see the list of test plans that were run with it on the web dashboard, for example:
https://linux.kernelci.org/test/job/mainline/branch/master/kernel/v5.13-rc4/
(on the main [jobs](https://linux.kernelci.org/jobs) page, click on the numbers with the test results.

There's also a section in the documentation, although it is very rough at the moment and just has some table with the initial LTP tests that were run from some early investigation:
https://kernelci.org/docs/tests/test-suites/
It should however get improved over time, and I think that would be the canonical place to learn about tests run by KernelCI.

About having different views on the web dashboard e.g. `test/plans`, there is some on-going work to come up with a new UI design with more flexible queries so this should be covered.  Maybe you could add a note to the user-experience stories discussion?
https://github.com/kernelci/kernelci-core/discussions/618

Thanks,
Guillaume

**Comment by pevik** [comment]
Thanks a lot for all info. I'll try to contribute to #618.
