### ISSUE TITLE
New test plan ltp-ima

### ISSUE THREAD

**Issue by pevik** [kernelci/kernelci-core#710]
Could you please create new test plan for [LTP IMA tests](https://github.com/linux-test-project/ltp/tree/master/testcases/kernel/security/integrity/ima/)?
They're maintained by me.
It'd be enough to run them on mainline, next tree and [Mimi Zohar's git tree on next-integrity-testing](https://git.kernel.org/pub/scm/linux/kernel/git/zohar/linux-integrity.git/log/?h=next-integrity-testing) (maintainer's branch).

**Comment by gctucker** [comment]
If this test is already built in the buster-ltp rootfs image we're using then this should be trivial.  I've added it to the backlog for this sprint, let's see if someone has the time to take a look.

**Comment by williamklin** [comment]
ltp-ima requires some specific kernel configs to work, do I need to build a new kernel for this, or just to choose whatever device types (in test_configs.yaml)  which already have these configs enabled to run?

**Comment by gctucker** [comment]
Sounds like having a new config fragment would be the best option.  Then we can decide when to build it, and the test plan would depend on the fragment to be in the build (for example, see `v4l2-compliance-vivid` which relies on the `virtualvideo` fragment).

**Comment by pevik** [comment]
Thanks a lot for working on this!
FYI all IMA required kernel options are in https://github.com/linux-test-project/ltp/tree/master/testcases/kernel/security/integrity/ima/. You can probably ignore EVM test just now, as it document unfixed problem on mainline.
