### ISSUE TITLE
Extend x86_64_defconfig to be able to support more drivers

### ISSUE THREAD

**Issue by eballetbo** [kernelci/kernelci-core#719]
The defconfig used to build amd64 kernels in KernelCI is very basic (basically the x86_64_defconfig + small fragment), in fact, is a minimal set of kernel config options. While is quite easy to upstream new config options for other platforms (like arm64 and armhf) it looks hard doing this for x86_64_defconfig.

If we want to have more coverage we need to enable more and more drivers in the kernel configuration. The purpose of this task is add a mechanism to be able to enable more drivers in amd64 kernel configs. As a first step, we can try to enable all the Cros-EC related drivers for Chromebooks.

**Comment by eballetbo** [comment]
From the cros-ec side, this fragment:
```
CONFIG_CHROME_PLATFORMS=y
CONFIG_CROS_EC=m
CONFIG_CROS_EC_LPC=m

CONFIG_IIO=m
CONFIG_IIO_CROS_EC_SENSORS_CORE=m
CONFIG_IIO_CROS_EC_SENSORS=m
```
Makes the cros-ec test results go from 0 tests

* https://lava.collabora.co.uk/results/3945366

to 7 tests passed.

* https://lava.collabora.co.uk/results/3946291

**Comment by sonnydeez** [comment]
So will try to find some more configs that help with octopus -- what are the other targets in the lab? Grunt maybe?

**Comment by eballetbo** [comment]
We have Grunt, Rammus, Sona and Coral too.

**Comment by gctucker** [comment]
@eballetbo Sounds like adding a `cros-ec` fragment?

**Comment by eballetbo** [comment]
It depends on how many fragments you want to deal with. That's one, but there are more to enable sound drivers, tpm, touchpad and touchscreen. Not sure if we should create a fragment for every feature or just a big fragment complementing the x86_64_defconfig.

**Comment by eballetbo** [comment]
Note that for ARM all these configs are includes in the default defconfig in the kernel.

**Comment by gctucker** [comment]
OK if this is intended to only be used on top of `x86_64_defconfig` then we may include it in the `x86-chromebook` fragment.

The only thing is that it's good to have a very minimal fragment to just boot Chromebooks, so we can more easily compare results with other x86 platforms that don't use any fragments.  So maybe we could keep `x86-chromebook` as small as possible, and just have one more e.g. `x86-chromebook-full` with all the options needed to fully enable everything.  That may actually be what #726 is really about though, and we could be building that on the chromeos.kernelci.org instance.

**Comment by gctucker** [comment]
Moving to the main KernelCI project board as this is now out of scope for the hackfest.
