### ISSUE TITLE
IGT on AMD GPU

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#743]
In the same way that we already have IGT running on i915 and Panfrost, this is about enabling it on AMD GPU.  Here's a high-level list of things to do:

- [x] #853
- [x] #854
- [x] #883

**Comment by gctucker** [comment]
Summary of the previous discussion on #740: 

* Firmware files: `stoney_*` binaries to be imported from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu into the `buster-igt` rootfs image.
* Initial list of test cases:
  * `amd_basic`
  * `amd_bypass`
  * `amd_color`
  * `amd_cs_nop`
  * `amd_info`
* Kernel config to enable: `CONFIG_DRM_AMDGPU=y`

**Comment by gctucker** [comment]
All merged, well done @nfraprado :tada:

**Comment by nfraprado** [comment]
Awesome, thank you for the help!
