### ISSUE TITLE
CIP DNS request (cip.kernelci.org)

### ISSUE THREAD

**Issue by aliceinwire** [kernelci/kernelci-core#780]
I would like to request a dns for CIP on cip.kernelci.org that points to https://linux.kernelci.org/job/cip/

thanks you

**Comment by gctucker** [comment]
This is going to be done using a `CNAME linux.kernelci.org` for `cip.kernelci.org` and an nginx config on the linux.kernelci.org server to redirect to `/job/cip`.

**Comment by gctucker** [comment]
For the record, here's DNS update request: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22812
(requires admin access)

**Comment by gctucker** [comment]
The DNS record has been updated and the nginx config added to redirect to the CIP jobs:
```
$ curl -I http://cip.kernelci.org
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 02 Sep 2021 08:21:42 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Keep-Alive: timeout=75
Location: https://linux.kernelci.org/job/cip/
```
The Let's Encrypt certificate has been updated to include the cip.kernelci.org subdomain too:
```
$ curl -I https://cip.kernelci.org
HTTP/2 301 
server: nginx
date: Thu, 02 Sep 2021 08:22:31 GMT
content-type: text/html
content-length: 178
location: https://linux.kernelci.org/job/cip/
strict-transport-security: max-age=31536000; preload
```

**Comment by aliceinwire** [comment]
thanks tested and works!

**Comment by gctucker** [comment]
Thanks for confirming.
