### ISSUE TITLE
Support IXP4XX testing

### ISSUE THREAD

**Issue by montjoie** [kernelci/kernelci-core#791]
I own an ARM Board based on IXP4XX SoC and I want it to ran kernelCI jobs.
The problem is that the default defconfig produces a BigEndian kernel and default armeb buildroot rootfs do not work on it. (init killed)

Major problem is that current armeb buildroot frags has:
BR2_GCC_TARGET_CPU="cortex-a5"

This is due to "configs/frags: armeb: update for ARMv7 only"

So probably we will not have any other choice than adding a new specific armeb rootfs.

**Comment by gctucker** [comment]
I see the IXP4XX chips are Intel's ARM XScale: https://en.wikipedia.org/wiki/XScale

So maybe we need some `xscale` variant for buildroot to run on your board, the article says it's based on the ARMv5TE architecture.
