### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#814]
**Is your feature request related to a problem? Please describe.**
The use of the Rust programming language is [being considered](https://lkml.org/lkml/2021/4/14/1023); it would be good to get CI coverage of patches sitting in linux-next. cc @ojeda @broonie 

**Describe the solution you'd like**
Availability of `rustc` in the environment.

**Comment by gctucker** [comment]
Nice one!  There should be all the bits in the current code to be able to enable that, with some new Docker images and potentially a few lines of code to handle build commands specific to Rust.  There's also some spare build capacity in our current clusters to enable that at least on linux-next.

**Comment by ojeda** [comment]
Related PR: https://github.com/kernelci/kernelci-core/pull/1468

Cc @10ne1

**Comment by gctucker** [comment]
I think all the initial elements are now in place, here's some sample build results:
https://linux.kernelci.org/build/id/63e32af52df46d582e8c864f/

Closing this issue now.  Any on-going maintenance to update `rustc` or fix anything is outside the initial scope of adding support for Rust builds.
