### ISSUE TITLE
dpkg -l is hanging on Bullseye

### ISSUE THREAD

**Issue by alexandrasp** [kernelci/kernelci-core#835]
During rootfs build using Debian Bullseye image as host _dpkg -l _ command is getting stuck.

**Comment by nuclearcat** [comment]
Is this issue still present?

**Comment by gctucker** [comment]
The answer is, yes and no: https://github.com/kernelci/kernelci-core/commit/7681d7888f67c82c5d7c0d0f3d6f4d79a513991a

The simple workaround is to not run `dpkg -l`.  Listing the packages was useful to keep track of what was actually left in the image at the end of the job, so it would be nice to properly fix it.
