### ISSUE TITLE
buster-libcamera build error

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#839]
The `buster-libcamera` rootfs is currently failing to build on all architectures (amd64, arm64, armhf) due to some out-of-space issue.  However, this doesn't appear to be a problem with the machine where it's being run as there is plenty of disk space left.  So it's more likely to be a debos configuration issue, with the space made available for the build.

To reproduce the problem, from inside a `kernelci/debos` Docker image:
```
$ ./kci_rootfs build --rootfs-config buster-libcamera --arch armhf --data-path config/rootfs/debos
[...]
2021/10/13 14:16:05 buster-libcamera.sh | /tmp/ccYoSgZj.s: Fatal error: can't close test/v4l2_videodevice/capture_async.p/capture_async.cpp.o: No space left on device
```

**Comment by nfraprado** [comment]
Fixed in #841.
