### ISSUE TITLE
Enable amdgpu driver in config fragment

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#854]
The `amdgpu` kernel driver is not enabled in `x86_64_defconfig`, so it needs to be done via a config fragment in [`build-configs.yaml`](https://github.com/kernelci/kernelci-core/blob/main/config/core/build-configs.yaml#L149).  This may be a new `amdgpu` fragment, with just the config options for the AMDGPU driver and maybe some related ones that are needed for this use-case.

Then the first platform where this would be used is the `hp-11A-G6-EE-grunt` AMD x86 Chromebook.  So there will need to be a build with both the `x86-chromebook` and the `amdgpu` fragments enabled.  Following the KernelCI naming convention for defconfigs, it will be `x86_64_defconfig+x86-chromebook+amdgpu`.

Steps:

* Determine which config options are required
* Add them as an `amdgpu` fragment in `build-configs.yaml`
* Create a PR - see tips on #853 
* Wait for [staging.kernelci.org](https://staging.kernelci.org) to pick up your changes, build a kernel with the fragment and run some tests
* Check that the build was produced as expected
* When combined with the changes to add the firmware files and to run IGT on the `grunt` platform, check that the `igt-gpu-amd` test results show that the `amdgpu` driver was correctly initialised.

**Comment by nfraprado** [comment]
In case this is used as a reference for newcomers to KernelCI in the future, I'll leave some more key points that helped me in making the PR at #886.

* In addition to adding the new fragment, the fragment needs to be added to the architectures that will use it in `build_configs_defaults`.
* To build a kernel with the new fragment and ensure it worked, `kci_build` was used. Its documentation shows this process: https://kernelci.org/docs/core/kci_build/. A config suitable to run on the `grunt` device was generated with `./kci_build make_config --defconfig=defconfig+x86-chromebook+amdgpu`.
* The resulting kernel was tested ([by submitting manually to LAVA](https://lava.collabora.co.uk/scheduler/job/5023017)) together with the rootfs containing igt and amdgpu firmware resulted from #884, and by running commands adapted from the [IGT lava test template](https://github.com/kernelci/kernelci-core/blob/main/config/lava/igt/igt.jinja2). They were:

```
export PATH=/usr/libexec/igt-gpu-tools:/usr/libexec/igt-gpu-tools/amdgpu:$PATH
export IGT_FORCE_DRIVER=amdgpu
/usr/bin/igt-parser.sh core_auth core_getclient core_getstats core_getversion core_setmaster_vs_auth gem_create amd_basic amd_bypass amd_color amd_cs_nop amd_info
```
(the igt tests were passed manually to `igt-parser.sh`, including the `amd_*` tests)
