### ISSUE TITLE
Debian Bullseye with clang-10

### ISSUE THREAD

**Issue by alexandrasp** [kernelci/kernelci-core#858]
There is not available a Debian package to Bullseye with clang-10, after I tried to update KernelCI clang-10 docker image and got some difficulties dues to some incompatible library versions we decided to report it and wait for someone working with Debian packages to update it before we tried to update our clang-10 docker image to Bullseye.

**Comment by nuclearcat** [comment]
I think after https://github.com/kernelci/kernelci-core/commit/b572fb297abf9b006c46b38dd7fb8a5df563848e we dont need clang-10 anymore?

**Comment by gctucker** [comment]
Yes, this can be closed now. In fact we kept a Buster image with clang-10 for a little while when it was still the minimum requirement in mainline kernel. Thanks for flagging this.
