### ISSUE TITLE
Draft: V4L2 Decoder Coverage

### ISSUE THREAD

**Issue by ndufresne** [kernelci/kernelci-core#866]
This issue is filed to try and document the aspect of covering V4L2 decoder testing in the future in KernelCI. Please edit freely the following text based on relevant discussions.  For those less familiar with CODEC in Linux, I'm adding a short overview.

## Linux CODEC Overview

CODEC stands for Coder and Decoder. Only decoders will be covered in this feature request. In the linux-media tree, there exist two types of decoders supported. They are named Sateful and Stateless. The state refers to what is being handled and stored inside the hardware, which the driver often cannot have access to (state that can be saved and restored is a special case and can exist in both types of HW). In order to decode complex video streams, the bitstream (the encoded data), needs to be parsed and interpreted. This information is processed according to the specification and the resulting state allows to calculate all the parameters to decode the following frame.

Stateful Decoders require a lot less work from userspace. Typical Linux drivers only require the data to be split in frames, while some don't even have this requirement. A non-exhaustive list of stateful decoders exist for the following SoC brands: Amlogic, NXP IMX6 (CODA driver), Qualcomm (VENUS driver), Samsung (MFC driver), Mediatek (on older Chromebooks) etc.

Stateless Drivers require a lot more work, as the bitstream needs to be converted into a series of related decode information with a large set of parameters. Some SoC brands include: Rockchip (Hantro and RkVdec), NXP IMX8M (Hantro), Allwinner (Cedrus), Mediatek (newer Chromebooks). 

## Solution Overview

There exist multiple ways we could do KernelCI CODEC testing. This solution aligns with linux-media maintainers' intent to require a conformance report along with the already in-place v4l2-compliance report when submitting a mainline CODEC.

The proposal is to run regression tests (verifying stable test results, as we know CODECs are not always compliant) using a tool called [Fluster](https://github.com/fluendo/fluster). This simple tool can download many publicly available conformance test vectors and validate various decoder implementations. The project is active and they have been helpful in getting V4L2 decoding support merged early. The tool already supports wrapping most of the reference decoders (this is to validate the hardness, these will produce perfect results of course), and already have large support for GStreamer and FFMPEG (including HW decoding). There is no restriction in Fluster upon what userland is wrapped for testing, this is very important I believe as we can't expect all vendors to guaranty FFMPEG or GStreamer support (even though it is encouraged).

Both FFMPEG and GStreamer have large support for stateful decoders. GStreamer is the only of the two to have upstream stateless support (MPEG2, VP8 and H264, the only stable CODEC API in linux-media stateless).  There is no strict requirement about which userspace is going to be used.

The testing will consist of running the conformance test, ideally with at least 2 parallel threads (unless strictly not supported by the HW). The result shall then be parsed and compared against saved previous results. If the result is stable, this is a success, if the result are better, the reference shall be updated and a positive report sent. If the result are negative, then the test is a failure and a bisection shall start.

A test takes from 2 to 6 minutes per CODEC to run on the SoCs we have tested so far. There is a lot of room for improvement in terms of test performance and I expect this to become lower over time. Only recently major CODECs were added to Fluster: VP9, VP9, H264, HEVC. We will add AV1 soon. Some legacy CODECs can't be tested that way, notably MPEG2, since the specification does not imply a bit-perfect decoded result. 

Fluster could be extended with fuzzy testing, but that requires storing the reference frames, which can be very large, and represent relatively high effort for CODECs that are not being used in new applications.

## Alternative Solution

As we have started working on a stub driver called vicodec, we have considered a different approach. This consists of a trace and retrace method. Basically, a reference V4L2 decoder implementation like FFMPEG or GStreamer could be run against the stub driver. This would produce a trace with all the interactions done with the Linux kernel (including a copy of the bitstream data). A standalone retrace tool would then be able to replay that trace on any real driver. The output could then be check-summed as-is for regression testing, or alternatively compared against a conformance frame checksum.

The benefit of such solution is that we no longer need to include media frameworks with the test system. Though, we'd have to produce and store these traces. There is a certain level of allowed behaviour difference between drivers, we may need per-HW (or per-HW type) traces. All the needed tools are not yet mainline or even implemented. This is not very practical considering we'd have to focus on the development of the tools rather than the KernelCI integration. We aren't pushing for this solution as we foresee that having usable GStreamer or FFMPEG support will be as simple as installing the appropriate packages using standard distributions like Debian or Fedora.

**Comment by gctucker** [comment]
See also: #181

**Comment by gctucker** [comment]
> The result shall then be parsed and compared against saved previous results.

This is something that KernelCI already does as post-processing, for all native tests being run.  For each failing test, it will check if the previous revision on the same branch, same platform and same type of kernel build passed or not.  If it passed, then a regression tracking starts.  Subsequent failures of the same test case will keep being added to the tracked regression.  Automated bisections will be automatically triggered, except at the moment not all test labs and not all kernel trees are being bisected by design.  The `linux-media` tree and the Collabora lab are enabled to run bisections so this should be good enough to start with.

**Comment by gctucker** [comment]
> Fluster could be extended with fuzzy testing, but that requires storing the reference frames, which can be very large

@ndufresne How large is a very large frame?  Using NFS root file system images, we could easily have MBs of data baked-in.

**Comment by gctucker** [comment]
About the alternative solution:

> Though, we'd have to produce and store these traces.

So we would most likely need to have a rootfs image to use with say, QEMU to generate the traces and store that in another rootfs image used on the real hardware.  This could actually be done as part of the rootfs image build jobs, which can include scripts with arbitrary commands.

**Comment by gctucker** [comment]
> All the needed tools are not yet mainline or even implemented. This is not very practical considering we'd have to focus on the development of the tools rather than the KernelCI integration.

@ndufresne Should we focus on the first solution then, and keep the alternative one as a potential alternative for sometime in the distant future?

**Comment by laura-nao** [comment]
Update on this subject: automated fluster tests are now running on `rk3399-gru-kevin` for H264, VP8 and VP9 decoders (enabled in `mainline` and `next` trees for now). If this solution proves to be stable, more tests can be added for different platforms and decoders.

**Comment by nuclearcat** [comment]
Question, does it mean issue is resolved? :)

**Comment by gctucker** [comment]
That's why have a DoD (Definition of Done) helps, if we can check all the boxes then the issue can be closed.

**Comment by ndufresne** [comment]
I don't think we need this issue anymore, as we agreed to use fluster to cover CODECs. Of course, plenty of upcoming work, enabling Chromebooks, enabling perhaps some stateful decoder. What wasn't covered in CODEC is Encoders, which only currently exist as stateful drivers. These are a different challenge to test, I don't expect kernelCI to develop these tests but instead start using third party tests when they exist.
