### ISSUE TITLE
Add igt-gpu-amd test plan

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#883]
Once the `amdgpu` kernel driver is being built with at least one config, the next step is to add a `igt-gpu-amd` test plan in `test-configs.yaml` with a list of relevant IGT test cases to run on a platform with an AMD GPU (probably grunt).

- [ ] List of test cases determined see this https://github.com/kernelci/kernelci-core/issues/743#issuecomment-870406385 as a starting point
- [ ] PR created to add the new test plan and enable it on `hp-11A-G6-EE-grunt` (or any other suitable platform)

**Comment by nfraprado** [comment]
There are two PRs here needed to start running the tests (not counting the ones from the previous steps in #743):
- [ ] #901 
- [ ] #890
