### ISSUE TITLE
buster-libcamera failing to build on arm64

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#887]
The `buster-libcamera` rootfs image is failing to build today with this error:
```
2021/11/18 23:47:20 buster-libcamera.sh | qemu: uncaught target signal 11 (Segmentation fault) - core dumped

2021/11/18 23:47:20 buster-libcamera.sh | /tmp/script/buster-libcamera.sh: line 50:  9907 Segmentation fault      meson build --prefix=/usr -Ddocumentation=disabled -Dgstreamer=disabled -Dpipelines=uvcvideo,rkisp1

2021/11/18 23:47:20 Action `Build testsuite` failed at stage Run, error: exit status 139
Powering off.
```
It built fine last week, the binaries can be found here:
https://storage.kernelci.org/images/rootfs/debian/buster-libcamera/20211112.0/arm64/

None of the other arm64 builds are failing, apart from buster-ltp but that's a known issue.  So it's most likely due to some changes in libcamera or its dependencies.

We may try with QEMU 6 from Debian backports as it's now available for Bullseye (the `kernelci/debos` Docker image is based on Bullseye).  We may also try to upgrade with `bullseye-libcamera` as we'll need to do that soon anyway, and the plain `bullseye` rootfs images are nearly ready for production.

**Comment by nfraprado** [comment]
A couple days ago, the way lc-compliance is built changed in libcamera: https://git.linuxtv.org/libcamera.git/commit/?id=0d50a04cc918e5122d1b22201cc949c2cfd337a5

Trying to compile lc-compliance locally using `kci_rootfs` in the `kernelci/debos` container reproduces the issue:
```
2021/11/19 14:24:06 buster-libcamera.sh | Downloading gtest source from https://github.com/google/googletest/archive/release-1.11.0.zip
2021/11/19 14:24:07 buster-libcamera.sh | Downloading file of unknown size.
2021/11/19 14:24:07 buster-libcamera.sh | Downloading gtest patch from https://wrapdb.mesonbuild.com/v2/gtest_1.11.0-1/get_patch
2021/11/19 14:24:08 buster-libcamera.sh | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2021/11/19 14:24:08 buster-libcamera.sh | /tmp/script/buster-libcamera.sh: line 50:  9907 Segmentation fault      meson build --prefix=/usr -Ddocumentation=disabled -Dgstreamer=disabled -Dpipelines=uvcvideo,rkisp1
2021/11/19 14:24:08 Action `Build testsuite` failed at stage Run, error: exit status 139
Powering off.
```

As can be seen, the issue happens while downloading gtest from meson's wrapdb. If the commit is reverted in the `buster-libcamera.sh` script after cloning, the compilation succeeds:
```
-git clone --depth=1 $LIBCAMERA_URL .
+git clone $LIBCAMERA_URL .
+
+git config --global user.email "you@example.com"
+git config --global user.name "Your Name"
+
+git revert --no-edit 0d50a04cc918e5122d1b22201cc949c2cfd337a5
```

Compiling natively (Archlinux) didn't reproduce the issue even with the troublesome commit present. So this looks like a qemu bug that manifests only when downloading from meson's wrapdb.

**Comment by gctucker** [comment]
OK, thank you for investigating this issue.  We can try with QEMU 6 from Bullseye backports, and if the issue is still there then revert that commit as a workaround until we've come up with a better way of building things from source.

**Comment by alexandrasp** [comment]
In the first try using Kernel CI docker image, I built locally the image installing qemu related packages from backports as you can see below.

```Get:75 http://deb.debian.org/debian bullseye-backports/main amd64 qemu-system-common amd64 1:6.1+dfsg-6~bpo11+1 [1835 kB]
Get:76 http://deb.debian.org/debian bullseye-backports/main amd64 qemu-system-data all 1:6.1+dfsg-6~bpo11+1 [1171 kB]
Get:77 http://deb.debian.org/debian bullseye/main amd64 seabios all 1.14.0-2 [149 kB]
Get:78 http://deb.debian.org/debian bullseye-backports/main amd64 qemu-system-x86 amd64 1:6.1+dfsg-6~bpo11+1 [8823 kB]
Get:79 http://deb.debian.org/debian bullseye-backports/main amd64 qemu-user-static amd64 1:6.1+dfsg-6~bpo11+1 [47.5 MB]
Get:80 http://deb.debian.org/debian bullseye/main amd64 systemd-container amd64 247.3-6 [441 kB]
``` 
``` 
2021/11/30 01:09:05 buster-libcamera.sh | Downloading: ..........
2021/11/30 01:09:05 buster-libcamera.sh | Downloading gtest patch from https://wrapdb.mesonbuild.com/v2/gtest_1.11.0-1/get_patch
2021/11/30 01:09:07 buster-libcamera.sh | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2021/11/30 01:09:07 buster-libcamera.sh | /tmp/script/buster-libcamera.sh: line 50:  9907 Segmentation fault      meson build --prefix=/usr -Ddocumentation=disabled -Dgstreamer=disabled -Dpipelines=uvcvideo,rkisp1
2021/11/30 01:09:07 Action `Build testsuite` failed at stage Run, error: exit status 139
Powering off.
```

In the second try using a debian testing (bookworm) debos package to build libcamera rootfs image to arm64 and again without success as you can see the log below. 

```
Get:29 http://deb.debian.org/debian bookworm/main amd64 qemu-system-common amd64 1:6.1+dfsg-8 [1,830 kB]
Get:30 http://deb.debian.org/debian bookworm/main amd64 qemu-system-data all 1:6.1+dfsg-8 [1,172 kB]
Get:31 http://deb.debian.org/debian bookworm/main amd64 seabios all 1.14.0-2 [149 kB]
Get:32 http://deb.debian.org/debian bookworm/main amd64 ipxe-qemu all 1.0.0+git-20190125.36a4c85-5.1 [766 kB]
Get:33 http://deb.debian.org/debian bookworm/main amd64 qemu-system-x86 amd64 1:6.1+dfsg-8 [8,761 kB]
Get:34 http://deb.debian.org/debian bookworm/main amd64 qemu-user-static amd64 1:6.1+dfsg-8 [47.6 MB]
```

```
2021/11/30 01:50:58 buster-libcamera.sh | Downloading gtest source from https://github.com/google/googletest/archive/release-1.11.0.zip
2021/11/30 01:50:58 buster-libcamera.sh | Downloading file of unknown size.
2021/11/30 01:50:59 buster-libcamera.sh | Downloading gtest patch from https://wrapdb.mesonbuild.com/v2/gtest_1.11.0-1/get_patch
2021/11/30 01:51:00 buster-libcamera.sh | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2021/11/30 01:51:00 buster-libcamera.sh | /tmp/script/buster-libcamera.sh: line 50:  9907 Segmentation fault      meson build --prefix=/usr -Ddocumentation=disabled -Dgstreamer=disabled -Dpipelines=uvcvideo,rkisp1
2021/11/30 01:51:00 Action `Build testsuite` failed at stage Run, error: exit status 139
Powering off.
```

@gctucker maybe it is time to revert the commit. 
@nfraprado could you share the version that you've compiled natively on Archlinux? Is it QEMU 6?

**Comment by alexandrasp** [comment]
About @nfraprado build, he was not talking about build rootfs image using Kernel CI scripts and debos, he just built the kernel from the source locally.

**Comment by gctucker** [comment]
The kernel has nothing to do with this issue.  Building libcamera from debos started failing after this commit: `0d50a04cc918e5122d1b22201cc949c2cfd337a5` which is the one we can revert in `buster-libcamera.sh`.

**Comment by nfraprado** [comment]
To clarify, as I mentioned above the test I did locally is to simply compile libcamera outside any virtualization/containerization (no docker container or QEMU). So I did not test generating the rootfs as a whole, just compiling libcamera since that's the step that is failing in the process.

From the testing it seemed like fetching from meson's wrapdb during compilation of libcamera stumbles in some edge case of some part of the virtualization used by the kernelci/debos container, since compiling outside virtualization doesn't have any issue. Hence we should try testing it again with the virtualization tools updated (QEMU, perhaps docker as well) to see if that solves it.

**Comment by gctucker** [comment]
I thought someone had already tested with QEMU from bullseye backports?

**Comment by gctucker** [comment]
> I thought someone had already tested with QEMU from bullseye backports?

Looking at earlier comments, this seems to be what Alex has tried and it failed in the same way.  So I think we should revert the patch in the script for now, report the issue to libcamera developers and then look for alternative ways to build test suites as debos wasn't really designed to be building source code anyway.
