### ISSUE TITLE
Add CIP to the automatically bisected kernel tree on production

### ISSUE THREAD

**Issue by aliceinwire** [kernelci/kernelci-core#922]
Having a bisection automatic log enabled on CIP kernel can make it easier to understand kernel problems.

**Comment by gctucker** [comment]
The cip tree has been added to the list both on staging and production (encrypted file):
https://github.com/kernelci/kernelci-jenkins-data/commit/95e87451af860d54a355bb18ee10db511d0c8e88

The changes will effectively be rolled out in production in the next update (Monday) but I've also added it by hand so it's already enabled.
