### ISSUE TITLE
Build failure of kselftest futex on KernelCI

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-core#981]
Build of futex kselftest fails every time on the server. kselftest build failure logs can be found [here](https://storage.kernelci.org/renesas/master/renesas-devel-2022-01-11-v5.16/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-10/logs/kselftest.log).

On my machine, I'm able to build the futex kselftest without any errors using kci_build commands. As I'm running 5.10, I've older header `/usr/include/linux/futex.h`. HEADERS_INSTALL config is also not enabled. When kselftests build command is executed:

1. it processes in tree uapi header files and put them into `<build>/usr/include/linux/futex.h`.
2. these `<build>/usr/include/linux/futex.h` headers are used for compilation of selftests. 

I don't know why the same thing is not happening on the server? On the server, I can find the processing of uapi headers, but later compilation seems like using older headers somehow and compilation fails. This should be debugged.

**Comment by musamaanjum** [comment]
Finally, I've found out that build of the futex selftest fails when built using kci_build tool, and kdir and output directories have different paths.

To reproduce this issue:
* Set kdir and output directories to different paths:
```
kdir: ../linux_mainline2
output: ../kci_0
```
* Run following in order:
```
./kci_build init_bmeta
./kci_build generate_fragments
./kci_build make_config --defconfig=x86_64_defconfig+x86-chromebook+kselftest
cp $config/x86_64_defconfig+x86-chromebook+kselftest ../kci_0/.config
./kci_build make_kselftest |& tee log
```
Here `x86_64_defconfig+x86-chromebook+kselftest` has been generated manually and replaced here to bypass another bug in KernelCI. Build failure log is attached: 
[errors.log](https://github.com/kernelci/kernelci-core/files/7853078/errors.log)

**Comment by musamaanjum** [comment]
This bug in `kci_build` affects all those kselftest that depend on the latest in tree uapi headers.

**Comment by gctucker** [comment]
There is a known issue due to some hard-coded paths in kselftest Makefiles that means the build won't work if using a separate build directory outside of the kernel source tree.  The KernelCI builds use a `build` directory as a sub-directory of the kernel source tree, so it's not quite the same as in the comment above where `kci_0` is outside of the source tree.

See the Kubernetes template where the build commands used in production are defined:
https://github.com/kernelci/kernelci-core/blob/main/config/k8s/job-build.jinja2

I'm pretty sure the build failure you've seen can be reproduced without using `kci_build`, just running make with a build directory outside the source tree.  But that's not what the production builds are doing, so it's not clear to me what the issue really is.  What do you think should be fixed?

**Comment by musamaanjum** [comment]
Yeah, it is problem in kselftest Makefiles. I'll report it in kernelci-project.

In job-build.jinja2, the output directory and KDIR are different, `output: ${KDIR}/build`. This is why kselftests build failure is reproducable. I've found a workaround for this issue. If we build kselftest from the build directory, the build works fine. We can update the behavior of `kci_build make_kselftest` such that instead of running `make -C tools/testing/selftests/ O=${OUTPUT}` inside the ${KDIR}, it should run `make -C source/tools/testing/selftests` inside ${OUTPUT}.

**Comment by gctucker** [comment]
I believe that if the output directory is the same as the source directory then kci_build will drop the `O=` argument.  Would that fix the issue?  If not then we would need to `cd ${OUTPUT}` before running `make -C` which is kind of hacky, and we may just keep a failing kselftest as that's where the issue should really be fixed.

**Comment by musamaanjum** [comment]
The build fails because the included paths are not correctly set by Makefile when O= is a different directory and linking fails. When O= to the same path, it'll not be dropped and linking will just get successful by chance.

I think kselftest Makefile just need to be corrected to include the correct include path when O= is used. This fix shouldn't take much time to do. I'll look into it.

**Comment by gctucker** [comment]
Right, so I think we may be able to work around the issue by setting `output` to the same value as `kdir` in the k8s builds.  But if we can get a fix for that applied then it would be even better.  I suspect there are many Makefiles in kselftest with the same problem though.

So maybe we should put the workaround in place anyway, and hopefully drop it once all the Makefile issue has been fixed.

**Comment by broonie** [comment]
There's definitely other issues with kselftest building with O= - the kselftest generic Makefiles don't really work properly there.

**Comment by musamaanjum** [comment]
https://github.com/kernelci/kernelci-project/issues/85 has fixed this. Patches should land in next soon.
