### ISSUE TITLE
Enable clang-14 builds for more Android branches

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-core#988]
Clang-14 has been enabled for the following android branches in the first pass:
- android12-5.10
- android12-5.10-lts
- android13-5.10
- android13-5.15

Check v5.4 onward android branches if they build with clang and enable them as well. Also, enable the following branches:
- mainline
- mainline_tracking

**Comment by musamaanjum** [comment]
**android-mainline:**
gki: builds fine

**android-mainline-tracking:**
gki:
* https://github.com/ClangBuiltLinux/linux/issues/1474, 3d5e7a28b1ea ("KVM: x86: avoid warning with -Wbitwise-instead-of-logical")

**android11-5.4, android12-5.4 and android12-5.4-lts:**
gki: A lot of warnings

**Comment by gctucker** [comment]
OK I think we could have mainline and mainline-tracking built on staging as well to get more coverage before rolling this out in production.
